Repository woowacourse-teams/2025-mul-kkam, pull requests merged in 2025-09, with the labels that each got.

#707 [BE/AN][chore]: 브랜치 전략 변경
  .github/workflows/backend-prod-cd.yml
  .github/workflows/main-pr-branch-guard.yml
Labels: AN, BE, 🚧 chore

#708 develop-be -> develop 병합 요청
  .github/workflows/backend-prod-cd.yml
  .github/workflows/main-pr-branch-guard.yml
Labels: BE

#710 [BE/AN][chore]: 브랜치 전략 변경
  backend/src/main/java/backend/mulkkam/MulKkamApplication.java
Labels: BE

#712 v1.0.1 릴리즈 요청
  .github/workflows/backend-prod-cd.yml
  .github/workflows/main-pr-branch-guard.yml
  backend/src/main/java/backend/mulkkam/MulKkamApplication.java
Labels: BE

#724 [BE][feat]: 기본 컵 리스트 조회
  backend/src/main/java/backend/mulkkam/common/exception/errorCode/InternalServerErrorErrorCode.java
  backend/src/main/java/backend/mulkkam/common/filter/JwtAuthenticationFilter.java
  backend/src/main/java/backend/mulkkam/cup/controller/CupController.java
  backend/src/main/java/backend/mulkkam/cup/domain/CupEmoji.java
  backend/src/main/java/backend/mulkkam/cup/domain/DefaultCup.java
  backend/src/main/java/backend/mulkkam/cup/domain/vo/CupEmojiUrl.java
  backend/src/main/java/backend/mulkkam/cup/dto/response/DefaultCupResponse.java
  backend/src/main/java/backend/mulkkam/cup/dto/response/DefaultCupsResponse.java
  backend/src/main/java/backend/mulkkam/cup/repository/CupEmojiRepository.java
  backend/src/main/java/backend/mulkkam/cup/service/CupService.java
  backend/src/main/java/backend/mulkkam/cup/support/CupFactory.java
  backend/src/main/java/backend/mulkkam/intake/domain/IntakeHistoryDetail.java
  backend/src/main/java/backend/mulkkam/member/service/MemberService.java
  backend/src/test/java/backend/mulkkam/cup/controller/CupControllerTest.java
  backend/src/test/java/backend/mulkkam/intake/service/IntakeHistoryServiceIntegrationTest.java
  backend/src/test/java/backend/mulkkam/member/controller/MemberControllerTest.java
  backend/src/test/java/backend/mulkkam/member/service/MemberServiceIntegrationTest.java
Labels: BE, ♻️ refactor, 🍯 feat, 🔨 fix

#722 [AN][fix]: 대표 컵 순서 라벨 오류
  android/app/src/main/java/com/mulkkam/ui/setting/SettingFragment.kt
  android/app/src/main/java/com/mulkkam/ui/setting/SettingViewModel.kt
  android/app/src/main/java/com/mulkkam/ui/settingcups/SettingCupsActivity.kt
  android/app/src/main/java/com/mulkkam/ui/settingcups/SettingCupsViewModel.kt
  android/app/src/main/java/com/mulkkam/ui/settingcups/adapter/SettingCupsAdapter.kt
  android/app/src/main/java/com/mulkkam/ui/settingcups/dialog/SettingCupFragment.kt
  android/app/src/main/java/com/mulkkam/ui/util/extensions/BundleExtensions.kt
  android/app/src/main/java/com/mulkkam/ui/util/extensions/IntentExtensions.kt
Labels: AN, 🔨 fix

#704 [AN][fix]: 입력 시 띄어쓰기 커서 오류 수정
  android/app/src/main/java/com/mulkkam/ui/custom/toast/CustomToast.kt
  android/app/src/main/java/com/mulkkam/ui/notification/NotificationActivity.kt
  android/app/src/main/java/com/mulkkam/ui/notification/adapter/NotificationViewHolder.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/nickname/NicknameFragment.kt
  android/app/src/main/java/com/mulkkam/ui/settingaccountinfo/SettingAccountInfoActivity.kt
  android/app/src/main/java/com/mulkkam/ui/settingaccountinfo/dialog/AccountDeleteDialogFragment.kt
  android/app/src/main/java/com/mulkkam/ui/settingnickname/SettingNicknameActivity.kt
Labels: AN, 🔨 fix

#742 [BE][feat]: 온보딩 endPoint 수정 - 칼리
  backend/src/main/java/backend/mulkkam/member/controller/OnboardingController.java
  backend/src/test/java/backend/mulkkam/MulKkamApplicationTests.java
  backend/src/test/java/backend/mulkkam/cup/controller/CupControllerTest.java
  backend/src/test/java/backend/mulkkam/member/controller/MemberControllerTest.java
Labels: BE

#743 [AN][refactor]: 로그인 시 온보딩 여부 확인 로직 변경
  android/app/src/main/java/com/mulkkam/data/remote/interceptor/AuthorizationInterceptor.kt
  android/app/src/main/java/com/mulkkam/data/remote/model/response/auth/AuthReissueResponse.kt
  android/app/src/main/java/com/mulkkam/data/remote/model/response/auth/AuthResponse.kt
  android/app/src/main/java/com/mulkkam/data/repository/AuthRepositoryImpl.kt
  android/app/src/main/java/com/mulkkam/domain/model/auth/AuthInfo.kt
  android/app/src/main/java/com/mulkkam/domain/repository/AuthRepository.kt
  android/app/src/main/java/com/mulkkam/ui/login/LoginViewModel.kt
Labels: AN, ♻️ refactor

#752 [BE][fix]: flyway 설정 오류 수정
  backend/src/main/resources/application-prod.yml
Labels: BE

#763 [BE][feat]: 토큰 관련 기기대응 로직 구현
  backend/src/main/resources/db/migration/common/V20250910_100000__add_device_uuid_to_account_refresh_token.sql
  backend/src/main/resources/db/migration/common/V20250910_150000__add_unique_key_to_account_refresh_token.sql
  backend/src/main/resources/db/migration/h2/V20250907_2150_update_device_uuid_in_account_refresh_token.sql
  backend/src/main/resources/db/migration/h2/V20250910_130000__update_device_uuid_in_account_refresh_token.sql
  backend/src/main/resources/db/migration/mysql/V20250907_2150_update_device_uuid_in_accout_refresh_token.sql
  backend/src/main/resources/db/migration/mysql/V20250910_130000__update_device_uuid_in_account_refresh_token.sql
Labels: BE

#807 [AN][fix]: 컵 수정 BottomSheet 버그 수정
  android/app/src/main/java/com/mulkkam/ui/onboarding/cups/dialog/CupBottomSheetViewModel.kt
  android/app/src/main/java/com/mulkkam/ui/settingcups/dialog/SettingCupViewModel.kt
Labels: AN, 🔨 fix

#805 [AN][feat]: 홈화면 인터렉션 구현
  android/app/src/main/java/com/mulkkam/domain/model/intake/IntakeHistorySummary.kt
  android/app/src/main/java/com/mulkkam/ui/history/HistoryFragment.kt
  android/app/src/main/java/com/mulkkam/ui/home/HomeFragment.kt
  android/app/src/main/java/com/mulkkam/ui/home/HomeViewModel.kt
  android/app/src/main/res/drawable/img_home_drink_character.xml
  android/app/src/main/res/layout/fragment_home.xml
  android/app/src/main/res/raw/lottie_home_confetti.json
Labels: AN, 🍯 feat

#812 [BE][feat]: 음용량 추가 요청의 응답에 음용 타입 추가
  backend/src/main/java/backend/mulkkam/intake/dto/CreateIntakeHistoryDetailResponse.java
  backend/src/main/java/backend/mulkkam/intake/service/IntakeHistoryService.java
Labels: BE

#814 [AN][refactor]: 커피 스낵바 문구 변경
  android/app/src/main/java/com/mulkkam/data/remote/model/response/intake/IntakeHistoryResultResponse.kt
  android/app/src/main/java/com/mulkkam/domain/model/intake/IntakeHistoryResult.kt
  android/app/src/main/java/com/mulkkam/domain/model/intake/IntakeInfo.kt
  android/app/src/main/java/com/mulkkam/ui/home/HomeFragment.kt
  android/app/src/main/java/com/mulkkam/ui/home/HomeViewModel.kt
  android/app/src/main/res/layout/layout_custom_snack_bar.xml
  android/app/src/main/res/values/strings.xml
Labels: AN, ♻️ refactor

#830 develop-an -> develop 머지
  android/.editorconfig
  android/app/build.gradle.kts
  android/app/proguard-rules.pro
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/mulkkam/data/checker/IntakeCheckerImpl.kt
  android/app/src/main/java/com/mulkkam/data/local/service/HealthService.kt
  android/app/src/main/java/com/mulkkam/data/remote/adapter/MulKkamCallAdapterFactory.kt
  android/app/src/main/java/com/mulkkam/data/remote/model/response/intake/IntakeHistoryResultResponse.kt
  android/app/src/main/java/com/mulkkam/data/remote/service/NotificationsService.kt
  android/app/src/main/java/com/mulkkam/data/work/IntakeWidgetWorker.kt
  android/app/src/main/java/com/mulkkam/data/work/IntakeWorker.kt
  android/app/src/main/java/com/mulkkam/di/HealthConnectInjection.kt
  android/app/src/main/java/com/mulkkam/di/WorkInjection.kt
  android/app/src/main/java/com/mulkkam/domain/checker/IntakeChecker.kt
  android/app/src/main/java/com/mulkkam/domain/model/intake/IntakeHistoryResult.kt
  android/app/src/main/java/com/mulkkam/domain/model/intake/IntakeHistorySummary.kt
  android/app/src/main/java/com/mulkkam/domain/model/intake/IntakeInfo.kt
  android/app/src/main/java/com/mulkkam/ui/custom/snackbar/CustomSnackBar.kt
  android/app/src/main/java/com/mulkkam/ui/designsystem/Color.kt
  android/app/src/main/java/com/mulkkam/ui/designsystem/Theme.kt
  android/app/src/main/java/com/mulkkam/ui/designsystem/Typography.kt
  android/app/src/main/java/com/mulkkam/ui/encyclopedia/CoffeeEncyclopediaActivity.kt
  android/app/src/main/java/com/mulkkam/ui/history/HistoryFragment.kt
  android/app/src/main/java/com/mulkkam/ui/home/HomeFragment.kt
  android/app/src/main/java/com/mulkkam/ui/home/HomeViewModel.kt
  android/app/src/main/java/com/mulkkam/ui/home/dialog/ManualDrinkFragment.kt
  android/app/src/main/java/com/mulkkam/ui/main/dialog/MainPermissionDialogFragment.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/cups/dialog/CupBottomSheetFragment.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/cups/dialog/CupBottomSheetViewModel.kt
  android/app/src/main/java/com/mulkkam/ui/settingcups/dialog/SettingCupFragment.kt
  android/app/src/main/java/com/mulkkam/ui/settingcups/dialog/SettingCupViewModel.kt
  android/app/src/main/java/com/mulkkam/ui/util/extensions/ContextExtensions.kt
  android/app/src/main/java/com/mulkkam/ui/widget/IntakeWidget.kt
  android/app/src/main/res/drawable/btn_snack_bar_action.xml
  android/app/src/main/res/drawable/img_home_drink_character.xml
  android/app/src/main/res/layout/activity_coffee_encyclopedia.xml
  android/app/src/main/res/layout/fragment_history.xml
  android/app/src/main/res/layout/fragment_home.xml
  android/app/src/main/res/layout/layout_custom_snack_bar.xml
  android/app/src/main/res/layout/layout_intake_widget.xml
  android/app/src/main/res/raw/lottie_home_confetti.json
  android/app/src/main/res/values/strings.xml
  android/gradle/libs.versions.toml
Labels: AN

#835 v2.0.1
  android/.editorconfig
  android/app/build.gradle.kts
  android/app/proguard-rules.pro
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/mulkkam/data/checker/IntakeCheckerImpl.kt
  android/app/src/main/java/com/mulkkam/data/local/service/HealthService.kt
  android/app/src/main/java/com/mulkkam/data/remote/adapter/MulKkamCallAdapterFactory.kt
  android/app/src/main/java/com/mulkkam/data/remote/model/response/intake/IntakeHistoryResultResponse.kt
  android/app/src/main/java/com/mulkkam/data/remote/service/NotificationsService.kt
  android/app/src/main/java/com/mulkkam/data/work/IntakeWidgetWorker.kt
  android/app/src/main/java/com/mulkkam/data/work/IntakeWorker.kt
  android/app/src/main/java/com/mulkkam/di/HealthConnectInjection.kt
  android/app/src/main/java/com/mulkkam/di/WorkInjection.kt
  android/app/src/main/java/com/mulkkam/domain/checker/IntakeChecker.kt
  android/app/src/main/java/com/mulkkam/domain/model/intake/IntakeHistoryResult.kt
  android/app/src/main/java/com/mulkkam/domain/model/intake/IntakeHistorySummary.kt
  android/app/src/main/java/com/mulkkam/domain/model/intake/IntakeInfo.kt
  android/app/src/main/java/com/mulkkam/ui/custom/snackbar/CustomSnackBar.kt
  android/app/src/main/java/com/mulkkam/ui/designsystem/Color.kt
  android/app/src/main/java/com/mulkkam/ui/designsystem/Theme.kt
  android/app/src/main/java/com/mulkkam/ui/designsystem/Typography.kt
  android/app/src/main/java/com/mulkkam/ui/encyclopedia/CoffeeEncyclopediaActivity.kt
  android/app/src/main/java/com/mulkkam/ui/history/HistoryFragment.kt
  android/app/src/main/java/com/mulkkam/ui/home/HomeFragment.kt
  android/app/src/main/java/com/mulkkam/ui/home/HomeViewModel.kt
  android/app/src/main/java/com/mulkkam/ui/home/dialog/ManualDrinkFragment.kt
  android/app/src/main/java/com/mulkkam/ui/main/dialog/MainPermissionDialogFragment.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/cups/dialog/CupBottomSheetFragment.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/cups/dialog/CupBottomSheetViewModel.kt
  android/app/src/main/java/com/mulkkam/ui/settingcups/dialog/SettingCupFragment.kt
  android/app/src/main/java/com/mulkkam/ui/settingcups/dialog/SettingCupViewModel.kt
  android/app/src/main/java/com/mulkkam/ui/util/extensions/ContextExtensions.kt
  android/app/src/main/java/com/mulkkam/ui/widget/IntakeWidget.kt
  android/app/src/main/res/drawable/btn_snack_bar_action.xml
  android/app/src/main/res/drawable/img_home_drink_character.xml
  android/app/src/main/res/layout/activity_coffee_encyclopedia.xml
  android/app/src/main/res/layout/fragment_history.xml
  android/app/src/main/res/layout/fragment_home.xml
  android/app/src/main/res/layout/layout_custom_snack_bar.xml
  android/app/src/main/res/layout/layout_intake_widget.xml
  android/app/src/main/res/raw/lottie_home_confetti.json
  android/app/src/main/res/values/strings.xml
  android/gradle/libs.versions.toml
  backend/src/main/java/backend/mulkkam/intake/dto/CreateIntakeHistoryDetailResponse.java
  backend/src/main/java/backend/mulkkam/intake/service/IntakeHistoryService.java
  backend/src/main/java/backend/mulkkam/member/service/OnboardingService.java
  backend/src/main/resources/application-prod.yml
Labels: AN

#847 [BE][feat]: 컵 디폴트 이미지 url 변경
  backend/src/main/java/backend/mulkkam/cup/domain/DefaultCup.java
  backend/src/main/java/backend/mulkkam/cup/repository/CupEmojiRepository.java
  backend/src/main/java/backend/mulkkam/cup/service/CupEmojiService.java
  backend/src/main/resources/db/migration/common/R__202509241258_modify_cup_emoji.sql
Labels: BE

#842 [AN][fix]: 1x4 위젯에서 원형 그래프가 잘리는 문제 해결
  android/app/src/main/res/layout/layout_intake_widget.xml
Labels: AN, 🔨 fix

#839 [AN][refactor]: 커피 스낵바 문구 변경
  android/app/src/main/res/values/strings.xml
Labels: AN, ♻️ refactor

#844 [BE][ refactor]: oauth_account 테이블 불필요한 칼럼 삭제
  backend/src/main/java/backend/mulkkam/intake/domain/TargetAmountSnapshot.java
  backend/src/main/java/backend/mulkkam/intake/service/IntakeAmountService.java
  backend/src/main/java/backend/mulkkam/member/service/OnboardingService.java
  backend/src/main/resources/db/migration/common/V20250923_200801__drop_deleted_at_oauth_account.sql
  backend/src/main/resources/db/migration/common/V20250924_143001__modify_updated_at_target_amount_snapshot.sql
  backend/src/main/resources/db/migration/common/V20250924_164501__drop_created_at_and_deleted_at_suggestion_notification.sql
Labels: BE, ♻️ refactor

#851 [AN][refactor]: 커피 백과사전 챗지피티 없애기
  android/app/src/main/res/values/strings.xml
Labels: AN, ♻️ refactor

#848 [AN][feat]: 홈 화면 컴포즈 적용
  android/app/build.gradle.kts
  android/app/src/main/java/com/mulkkam/ui/component/ColoredText.kt
  android/app/src/main/java/com/mulkkam/ui/component/NetworkImage.kt
  android/app/src/main/java/com/mulkkam/ui/custom/floatingactionbutton/ExtendableFloatingActionButton.kt
  android/app/src/main/java/com/mulkkam/ui/custom/floatingactionbutton/ExtendableFloatingMenu.kt
  android/app/src/main/java/com/mulkkam/ui/custom/floatingactionbutton/ExtendableFloatingMenuIcon.kt
  android/app/src/main/java/com/mulkkam/ui/custom/floatingactionbutton/ExtendableFloatingMenuItem.kt
  android/app/src/main/java/com/mulkkam/ui/custom/progress/LinearGradientProgressBarView.kt
  android/app/src/main/java/com/mulkkam/ui/home/HomeFragment.kt
  android/app/src/main/java/com/mulkkam/ui/home/HomeScreen.kt
  android/app/src/main/java/com/mulkkam/ui/home/HomeViewModel.kt
  android/app/src/main/java/com/mulkkam/ui/home/component/DrinkButton.kt
  android/app/src/main/java/com/mulkkam/ui/home/component/DrinkCupOption.kt
  android/app/src/main/java/com/mulkkam/ui/home/component/DrinkMenu.kt
  android/app/src/main/java/com/mulkkam/ui/home/component/DrinkMenuItem.kt
  android/app/src/main/java/com/mulkkam/ui/home/component/HomeCharacter.kt
  android/app/src/main/java/com/mulkkam/ui/home/component/HomeConfetti.kt
  android/app/src/main/java/com/mulkkam/ui/home/component/HomeProgressOverview.kt
  android/app/src/main/java/com/mulkkam/ui/home/component/HomeTopBar.kt
  android/app/src/main/java/com/mulkkam/ui/home/component/LinearGradientProgress.kt
  android/app/src/main/java/com/mulkkam/ui/home/component/NotificationCounter.kt
  android/app/src/main/java/com/mulkkam/ui/home/component/RoundIconButton.kt
  android/app/src/main/java/com/mulkkam/ui/home/model/HomeUiStateHolder.kt
  android/app/src/main/java/com/mulkkam/ui/util/extensions/ModifierExtensions.kt
  android/app/src/main/java/com/mulkkam/ui/util/extensions/StringExtensions.kt
  android/app/src/main/res/drawable/img_cup_placeholder.xml
  android/app/src/main/res/drawable/img_placeholder.xml
  android/app/src/main/res/layout/activity_splash.xml
  android/app/src/main/res/layout/fragment_home.xml
  android/app/src/main/res/layout/layout_expandable_floating_action_button.xml
  android/app/src/main/res/layout/layout_expandable_floating_menu.xml
  android/app/src/main/res/values/strings.xml
  android/gradle/libs.versions.toml
Labels: AN, 🍯 feat

#860 [BE][fix]: 알림 삭제 조인 쿼리 수정
  backend/src/main/java/backend/mulkkam/notification/repository/NotificationRepository.java
Labels: BE

#864 [BE][feat]: 알림 조회 로직 DTO 기반 리팩터링 및 읽음 처리 최적화
  backend/src/main/java/backend/mulkkam/notification/controller/NotificationController.java
  backend/src/main/java/backend/mulkkam/notification/dto/GetNotificationResponse.java
  backend/src/main/java/backend/mulkkam/notification/dto/GetSuggestionNotificationResponse.java
  backend/src/main/java/backend/mulkkam/notification/dto/ReadNotificationRow.java
  backend/src/main/java/backend/mulkkam/notification/repository/NotificationRepository.java
  backend/src/main/java/backend/mulkkam/notification/service/NotificationService.java
  backend/src/test/java/backend/mulkkam/notification/controller/NotificationControllerTest.java
  backend/src/test/java/backend/mulkkam/notification/controller/SuggestionNotificationControllerTest.java
  backend/src/test/java/backend/mulkkam/notification/service/NotificationServiceIntegrationTest.java
  backend/src/test/java/backend/mulkkam/notification/service/NotificationServiceUnitTest.java
  backend/src/test/java/backend/mulkkam/notification/service/SuggestionNotificationIntegrationServiceTest.java
  backend/src/test/java/backend/mulkkam/notification/service/SuggestionNotificationUnitServiceTest.java
  backend/src/test/java/backend/mulkkam/support/fixture/notification/NotificationFixtureBuilder.java
  backend/src/test/java/backend/mulkkam/support/fixture/notification/SuggestionNotificationFixtureBuilder.java
Labels: BE

#866 [BE][fix]: 예외 발생 시 로깅 개선
  backend/src/main/resources/logback-spring.xml
Labels: BE
