Repository woowacourse-teams/2025-mul-kkam, pull requests merged in 2025-07, with the labels that each got.

#9 [AN/BE][fix]: Issue 템플릿이 적용되지 않는 오류 해결
  .github/ISSUE_TEMPLATE/default_issue_template.md
Labels: 🤖 AN, 🧞‍♂️ BE, 🔨 fix

#10 [AN][style]: 디자인 시스템 구축
  android/app/src/main/res/font/pretendard_black.ttf
  android/app/src/main/res/font/pretendard_bold.ttf
  android/app/src/main/res/font/pretendard_extra_bold.ttf
  android/app/src/main/res/font/pretendard_extra_light.ttf
  android/app/src/main/res/font/pretendard_light.ttf
  android/app/src/main/res/font/pretendard_medium.ttf
  android/app/src/main/res/font/pretendard_regular.ttf
  android/app/src/main/res/font/pretendard_semi_bold.ttf
  android/app/src/main/res/font/pretendard_thin.ttf
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/typography.xml
Labels: 🤖 AN, 🎨 style

#14 [AN][feat]: 위치 권한 요청 기능 구현
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/seulseul/ui/binding/BindingActivity.kt
  android/app/src/main/java/com/seulseul/ui/main/MainActivity.kt
  android/app/src/main/res/values/strings.xml
Labels: 🤖 AN, 🍯 feat

#13 [BE/AN][fix]: Issue 템플릿 내의 부모 이슈 주석 처리
  .github/ISSUE_TEMPLATE/default_issue_template.md
Labels: 🤖 AN, 🧞‍♂️ BE, 🔨 fix

#22 [AN][chore]: 기획에 필요한 플러그인 및 라이브러리 추가
  android/app/build.gradle.kts
  android/build.gradle.kts
  android/gradle/libs.versions.toml
  android/settings.gradle.kts
Labels: 🤖 AN, 🚧 chore

#25 [AN][feat]: Android CI Github Workflow 적용
  .github/workflows/android.yml
  android/app/src/androidTest/java/com/seulseul/.gitkeep
  android/app/src/androidTest/java/com/seulseul/ExampleInstrumentedTest.kt
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/seulseul/AddScheduleActivity.kt
  android/app/src/main/java/com/seulseul/di/NetworkInjection.kt
  android/app/src/main/java/com/seulseul/ui/main/MainActivity.kt
  android/app/src/main/res/layout/activity_add_schedule.xml
  android/app/src/main/res/xml/network_security_config.xml
  android/app/src/test/java/com/seulseul/.gitkeep
  android/app/src/test/java/com/seulseul/ExampleUnitTest.kt
  android/build.gradle.kts
  android/gradle/libs.versions.toml
  android/gradle/wrapper/gradle-wrapper.jar
Labels: 🤖 AN, 🍯 feat

#28 [AN][refactor]: 프로젝트 세팅 수정
  android/app/build.gradle.kts
  android/app/src/androidTest/java/com/mulkkam/.gitkeep
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/mulkkam/MulKkamApp.kt
  android/app/src/main/java/com/mulkkam/data/local/.gitkeep
  android/app/src/main/java/com/mulkkam/data/remote/service/.gitkeep
  android/app/src/main/java/com/mulkkam/di/NetworkInjection.kt
  android/app/src/main/java/com/mulkkam/ui/binding/BindingActivity.kt
  android/app/src/main/java/com/mulkkam/ui/binding/BindingFragment.kt
  android/app/src/main/java/com/mulkkam/ui/main/MainActivity.kt
  android/app/src/main/java/com/mulkkam/util/.gitkeep
  android/app/src/main/java/com/seulseul/data/remote/service/RouteService.kt
  android/app/src/main/java/com/seulseul/ui/main/MainActivity.kt
  android/app/src/main/res/drawable/bg_add_schedule_rectangle_8dp.xml
  android/app/src/main/res/drawable/bg_add_schedule_rectangle_bottom_12dp.xml
  android/app/src/main/res/drawable/btn_add_schedule_minus.xml
  android/app/src/main/res/drawable/btn_add_schedule_plus.xml
  android/app/src/main/res/drawable/ic_add_schedule_arrival.xml
  android/app/src/main/res/drawable/ic_add_schedule_calendar.xml
  android/app/src/main/res/drawable/ic_add_schedule_departure.xml
  android/app/src/main/res/drawable/ic_add_schedule_paper_plane.xml
  android/app/src/main/res/drawable/ic_add_schedule_preparation_time.xml
  android/app/src/main/res/drawable/ic_add_schedule_timer.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/values/themes.xml
  android/app/src/test/java/com/mulkkam/.gitkeep
  android/settings.gradle.kts
Labels: 🤖 AN, ♻️ refactor

#41 [BE][chore]: 백엔드 CI 워크플로우 추가
  .github/workflows/backend-ci.yml
Labels: 🧞‍♂️ BE, 🚧 chore

#37 [AN][feat]: 기록 화면 UI 구현
  android/app/src/main/java/com/mulkkam/domain/DailyWaterIntake.kt
  android/app/src/main/java/com/mulkkam/domain/WaterRecord.kt
  android/app/src/main/java/com/mulkkam/ui/record/RecordFragment.kt
  android/app/src/main/java/com/mulkkam/ui/record/adapter/RecordAdapter.kt
  android/app/src/main/java/com/mulkkam/ui/record/adapter/WaterRecordViewHolder.kt
  android/app/src/main/res/layout/fragment_record.xml
  android/app/src/main/res/layout/item_water_record.xml
  android/app/src/main/res/values/strings.xml
Labels: 🤖 AN, 🍯 feat

#43 [BE][chore] CI/CD 파이프라인 구축
  .github/workflows/backend-cd.yml
  .github/workflows/backend-ci.yml
  backend/Dockerfile
  backend/src/main/java/backend/mulkkam/MulKkamApplication.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-local.yml
  backend/src/main/resources/application.yml
  backend/src/test/java/backend/mulkkam/cup/CupFixture.java
  backend/src/test/java/backend/mulkkam/cup/service/CupServiceTest.java
Labels: 🧞‍♂️ BE, 🚧 chore

#57 [BE][feat]: 음수량 기록 기능 구현
  backend/src/main/java/backend/mulkkam/intake/controller/IntakeHistoryController.java
  backend/src/main/java/backend/mulkkam/intake/domain/IntakeHistory.java
  backend/src/main/java/backend/mulkkam/intake/dto/IntakeHistoryCreateRequest.java
  backend/src/main/java/backend/mulkkam/intake/repository/IntakeHistoryRepository.java
  backend/src/main/java/backend/mulkkam/intake/service/IntakeHistoryService.java
  backend/src/main/java/backend/mulkkam/member/domain/Member.java
  backend/src/main/resources/application.yml
  backend/src/test/java/backend/mulkkam/intake/service/IntakeHistoryServiceIntegrationTest.java
  backend/src/test/java/backend/mulkkam/intake/service/IntakeHistoryServiceUnitTest.java
  backend/src/test/java/backend/mulkkam/support/DatabaseCleaner.java
  backend/src/test/java/backend/mulkkam/support/IntakeHistoryFixture.java
  backend/src/test/java/backend/mulkkam/support/MemberFixture.java
  backend/src/test/java/backend/mulkkam/support/ServiceIntegrationTest.java
Labels: 🧞‍♂️ BE, 🍯 feat

#46 [AN][feat]: 일주일 차트 클릭리스너 구현
  android/app/src/main/java/com/mulkkam/domain/DailyWaterIntake.kt
  android/app/src/main/java/com/mulkkam/domain/WaterRecords.kt
  android/app/src/main/java/com/mulkkam/ui/record/RecordFragment.kt
  android/app/src/main/java/com/mulkkam/ui/record/RecordViewModel.kt
  android/app/src/main/java/com/mulkkam/ui/record/adapter/RecordAdapter.kt
Labels: 🤖 AN, 🍯 feat

#64 [BE][feat]: 사용자 몸무게 및 성별 저장
  backend/src/main/java/backend/mulkkam/common/exception/BadRequestErrorCode.java
  backend/src/main/java/backend/mulkkam/common/exception/CommonException.java
  backend/src/main/java/backend/mulkkam/common/exception/ErrorCode.java
  backend/src/main/java/backend/mulkkam/common/exception/ErrorResponse.java
  backend/src/main/java/backend/mulkkam/common/exception/FailureBody.java
  backend/src/main/java/backend/mulkkam/common/exception/GlobalExceptionHandler.java
  backend/src/main/java/backend/mulkkam/common/exception/NotFoundErrorCode.java
  backend/src/main/java/backend/mulkkam/member/controller/MemberController.java
  backend/src/main/java/backend/mulkkam/member/domain/Member.java
  backend/src/main/java/backend/mulkkam/member/domain/vo/PhysicalAttributes.java
  backend/src/main/java/backend/mulkkam/member/dto/PhysicalAttributesModifyRequest.java
  backend/src/main/java/backend/mulkkam/member/service/MemberService.java
  backend/src/main/resources/application-dev.yml
  backend/src/test/java/backend/mulkkam/member/service/MemberServiceIntegrationTest.java
  backend/src/test/java/backend/mulkkam/member/service/MemberServiceUnitTest.java
  backend/src/test/java/backend/mulkkam/support/MemberFixture.java
Labels: 🧞‍♂️ BE, 🍯 feat

#69 [BE][feat]: 날짜에 따른 음용량 조회
  backend/src/main/java/backend/mulkkam/common/exception/BadRequestErrorCode.java
  backend/src/main/java/backend/mulkkam/intake/controller/IntakeHistoryController.java
  backend/src/main/java/backend/mulkkam/intake/dto/DateRangeRequest.java
  backend/src/main/java/backend/mulkkam/intake/dto/IntakeHistoryResponse.java
  backend/src/main/java/backend/mulkkam/intake/dto/IntakeHistorySummaryResponse.java
  backend/src/main/java/backend/mulkkam/intake/repository/IntakeHistoryRepository.java
  backend/src/main/java/backend/mulkkam/intake/service/IntakeHistoryService.java
  backend/src/test/java/backend/mulkkam/intake/repository/IntakeHistoryRepositoryTest.java
  backend/src/test/java/backend/mulkkam/intake/service/IntakeHistoryServiceIntegrationTest.java
  backend/src/test/java/backend/mulkkam/intake/service/IntakeHistoryServiceUnitTest.java
Labels: 🧞‍♂️ BE, 🍯 feat

#77 [BE][fix]: 잘못된 dto 형태 수정
  backend/src/main/java/backend/mulkkam/intake/controller/IntakeAmountController.java
  backend/src/main/java/backend/mulkkam/intake/controller/IntakeHistoryController.java
  backend/src/main/java/backend/mulkkam/intake/dto/IntakeHistoryResponse.java
  backend/src/main/java/backend/mulkkam/intake/service/IntakeHistoryService.java
Labels: 🧞‍♂️ BE, 🔨 fix

#80 [BE][feat]: API 명세서 CORS 해결
  backend/src/main/java/backend/mulkkam/common/config/WebConfiguration.java
Labels: 🧞‍♂️ BE, 🍯 feat

#97 [BE][fix]: Amount 가 0 이 되지 않도록 수정 및 달성률 계산 로직 수정
  backend/src/main/java/backend/mulkkam/intake/domain/vo/AchievementRate.java
  backend/src/main/java/backend/mulkkam/intake/domain/vo/Amount.java
  backend/src/main/java/backend/mulkkam/intake/service/IntakeHistoryService.java
  backend/src/test/java/backend/mulkkam/intake/domain/vo/AchievementRateTest.java
  backend/src/test/java/backend/mulkkam/intake/domain/vo/AmountTest.java
Labels: 🧞‍♂️ BE, 🔨 fix

#100 [BE][fix]: 응답 수정
  backend/src/main/java/backend/mulkkam/cup/dto/response/CupResponse.java
  backend/src/test/java/backend/mulkkam/cup/service/CupServiceIntegrationTest.java
  backend/src/test/java/backend/mulkkam/cup/service/CupServiceUnitTest.java
Labels: 🧞‍♂️ BE, 🔨 fix

#105 [BE][fix]: 달성률 소수점까지 도출되도록 수정
  backend/src/main/java/backend/mulkkam/intake/dto/IntakeHistorySummaryResponse.java
Labels: 🧞‍♂️ BE, 🔨 fix

#93 [AN][feat]: 물컵 설정 뷰 API 연결
  android/app/src/main/java/com/mulkkam/data/remote/model/request/AddCupRequest.kt
  android/app/src/main/java/com/mulkkam/data/remote/service/CupsService.kt
  android/app/src/main/java/com/mulkkam/data/repository/CupsRepository.kt
  android/app/src/main/java/com/mulkkam/di/NetworkInjection.kt
  android/app/src/main/java/com/mulkkam/di/RepositoryInjection.kt
  android/app/src/main/java/com/mulkkam/ui/settingwater/SettingWaterActivity.kt
  android/app/src/main/java/com/mulkkam/ui/settingwater/dialog/SettingWaterCupFragment.kt
  android/app/src/main/java/com/mulkkam/ui/settingwater/dialog/SettingWaterCupViewModel.kt
  android/app/src/main/java/com/mulkkam/ui/settingwater/model/CupUiModel.kt
  android/app/src/main/res/layout/fragment_setting_water_cup.xml
Labels: 🤖 AN, 🍯 feat

#102 [AN][refactor]: 기록 관련 코드 리팩터링
  android/app/src/main/java/com/mulkkam/ui/history/HistoryFragment.kt
  android/app/src/main/java/com/mulkkam/ui/history/HistoryViewModel.kt
  android/app/src/main/java/com/mulkkam/ui/history/adapter/HistoryAdapter.kt
  android/app/src/main/java/com/mulkkam/ui/history/adapter/HistoryViewHolder.kt
  android/app/src/main/java/com/mulkkam/ui/model/MainTab.kt
  android/app/src/main/java/com/mulkkam/ui/record/RecordViewModel.kt
  android/app/src/main/java/com/mulkkam/ui/record/adapter/RecordAdapter.kt
  android/app/src/main/java/com/mulkkam/ui/record/adapter/WaterRecordViewHolder.kt
  android/app/src/main/res/drawable/btn_history_week_next.xml
  android/app/src/main/res/drawable/btn_history_week_prev.xml
  android/app/src/main/res/drawable/img_history_character.png
  android/app/src/main/res/layout/fragment_history.xml
  android/app/src/main/res/layout/history_water_intake_chart.xml
  android/app/src/main/res/layout/item_intake_history.xml
  android/app/src/main/res/menu/menu_bottom_nav.xml
  android/app/src/main/res/values/strings.xml
Labels: 🤖 AN, ♻️ refactor

#103 [AN][refactor]: Refreshable이 이미 생성된 뷰에서만 작동하도록 수정
  android/app/src/main/java/com/mulkkam/ui/history/HistoryFragment.kt
  android/app/src/main/java/com/mulkkam/ui/home/HomeFragment.kt
  android/app/src/main/java/com/mulkkam/ui/main/MainActivity.kt
  android/app/src/main/java/com/mulkkam/ui/main/Refreshable.kt
  android/app/src/main/java/com/mulkkam/ui/setting/SettingFragment.kt
Labels: 🤖 AN, ♻️ refactor

#112 [AN][style]: 홈 화면 디자인 디테일 수정
  android/app/src/main/res/drawable/ic_home_drink.png
  android/app/src/main/res/drawable/ic_home_drink.xml
  android/app/src/main/res/drawable/ic_home_notification.xml
  android/app/src/main/res/layout/fragment_home.xml
  android/app/src/main/res/values/strings.xml
Labels: 🤖 AN, 🎨 style

#115 [AN][refactor]: 안드로이드 앱 버전 변경
  android/gradle/libs.versions.toml
Labels: 🤖 AN, ♻️ refactor

#118 [BE][refactor] GlobalExceptionHandler에서 메서드명 수정
  backend/src/main/java/backend/mulkkam/common/exception/GlobalExceptionHandler.java
Labels: 🧞‍♂️ BE, ♻️ refactor

#124 [BE][refactor]: 컵 관련 리팩터링 진행
  backend/src/main/java/backend/mulkkam/cup/domain/vo/CupRank.java
  backend/src/main/java/backend/mulkkam/cup/dto/request/CupRegisterRequest.java
  backend/src/main/java/backend/mulkkam/cup/service/CupService.java
  backend/src/test/java/backend/mulkkam/cup/domain/vo/CupAmountTest.java
  backend/src/test/java/backend/mulkkam/cup/domain/vo/CupNicknameTest.java
  backend/src/test/java/backend/mulkkam/cup/domain/vo/CupRankTest.java
Labels: 🧞‍♂️ BE, ♻️ refactor

#131 [AN][refactor]: 차트 라이브러리를 커스텀 뷰로 변경
  android/app/build.gradle.kts
  android/app/src/main/java/com/mulkkam/ui/custom/GradientDonutChartView.kt
  android/app/src/main/java/com/mulkkam/ui/history/HistoryFragment.kt
  android/app/src/main/res/layout/history_water_intake_chart.xml
  android/gradle/libs.versions.toml
Labels: AN, ♻️ refactor

#121 [BE][feat]: 사용자 목표 음용량 조회
  backend/src/main/java/backend/mulkkam/intake/controller/IntakeAmountController.java
  backend/src/main/java/backend/mulkkam/intake/dto/IntakeRecommendedAmountResponse.java
  backend/src/main/java/backend/mulkkam/intake/dto/IntakeTargetAmountModifyRequest.java
  backend/src/main/java/backend/mulkkam/intake/dto/IntakeTargetAmountResponse.java
  backend/src/main/java/backend/mulkkam/intake/service/IntakeAmountService.java
  backend/src/test/java/backend/mulkkam/intake/service/IntakeAmountServiceIntegrationTest.java
  backend/src/test/java/backend/mulkkam/intake/service/IntakeAmountServiceUnitTest.java
Labels: BE, 🍯 feat

#146 [AN][feat]: 홈 화면 오늘 기록 조회 기능 추가
  android/app/src/main/java/com/mulkkam/data/remote/model/response/IntakeTargetAmountResponse.kt
  android/app/src/main/java/com/mulkkam/data/remote/service/IntakeService.kt
  android/app/src/main/java/com/mulkkam/data/repository/IntakeRepository.kt
  android/app/src/main/java/com/mulkkam/ui/history/HistoryViewModel.kt
  android/app/src/main/java/com/mulkkam/ui/home/HomeFragment.kt
  android/app/src/main/java/com/mulkkam/ui/home/HomeViewModel.kt
  android/app/src/main/res/layout/fragment_home.xml
  android/app/src/main/res/values/strings.xml
Labels: AN, 🍯 feat

#145 [AN][feat]: 홈 화면 컵 용량 버튼 추가
  android/app/src/main/java/com/mulkkam/ui/home/HomeFragment.kt
  android/app/src/main/java/com/mulkkam/ui/home/HomeViewModel.kt
  android/app/src/main/res/layout/fragment_home.xml
Labels: AN, 🍯 feat

#119 [BE][feat]: 목표 달성률 계산 로직 변경
  backend/src/main/java/backend/mulkkam/intake/domain/vo/AchievementRate.java
  backend/src/main/java/backend/mulkkam/intake/dto/IntakeHistoryResponse.java
  backend/src/main/java/backend/mulkkam/intake/service/IntakeHistoryService.java
  backend/src/test/java/backend/mulkkam/cup/repository/CupRepositoryTest.java
  backend/src/test/java/backend/mulkkam/cup/service/CupServiceIntegrationTest.java
  backend/src/test/java/backend/mulkkam/cup/service/CupServiceUnitTest.java
  backend/src/test/java/backend/mulkkam/intake/repository/IntakeHistoryRepositoryTest.java
  backend/src/test/java/backend/mulkkam/intake/service/IntakeAmountServiceIntegrationTest.java
  backend/src/test/java/backend/mulkkam/intake/service/IntakeAmountServiceUnitTest.java
  backend/src/test/java/backend/mulkkam/intake/service/IntakeHistoryServiceIntegrationTest.java
  backend/src/test/java/backend/mulkkam/intake/service/IntakeHistoryServiceUnitTest.java
  backend/src/test/java/backend/mulkkam/member/service/MemberServiceIntegrationTest.java
  backend/src/test/java/backend/mulkkam/member/service/MemberServiceUnitTest.java
  backend/src/test/java/backend/mulkkam/support/CupFixtureBuilder.java
  backend/src/test/java/backend/mulkkam/support/IntakeHistoryFixtureBuilder.java
  backend/src/test/java/backend/mulkkam/support/MemberFixture.java
  backend/src/test/java/backend/mulkkam/support/MemberFixtureBuilder.java
Labels: BE, 🍯 feat

#151 [AN][feat]: 홈 화면 음용량 기록 API
  android/app/src/main/java/com/mulkkam/data/remote/model/request/IntakeHistoryRequest.kt
  android/app/src/main/java/com/mulkkam/data/remote/service/IntakeService.kt
  android/app/src/main/java/com/mulkkam/data/repository/IntakeRepository.kt
  android/app/src/main/java/com/mulkkam/ui/home/HomeFragment.kt
  android/app/src/main/java/com/mulkkam/ui/home/HomeViewModel.kt
  android/app/src/main/res/layout/fragment_home.xml
Labels: AN, 🍯 feat

#155 [BE][chore] flyway 세팅
  backend/build.gradle
  backend/src/main/java/backend/mulkkam/member/domain/Member.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-local.yml
  backend/src/main/resources/application-test.yml
  backend/src/main/resources/db/migration/V1__init.sql
Labels: BE, 🚧 chore

#175 [BE/AN][feat]: pr 제목을 issue 제목과 동기화하도록 workflow 설정
  .github/workflows/pr-title-sync.yml
Labels: AN, BE, 🍯 feat

#165 [AN[refactor]: 바텀 네비게이션 홈 화면 아이콘 굵기 수정
  android/app/src/main/res/drawable/ic_home.xml
Labels: AN, 🎨 style

#173 [BE][feat]: swagger 연동
  backend/build.gradle
  backend/src/main/java/backend/mulkkam/common/config/SwaggerConfig.java
Labels: BE, 🍯 feat

#193 [BE/AN][feat]: pr-title-init.yml 이벤트 발생 조건 수정
  .github/workflows/pr-title-init.yml
Labels: AN, BE, 📄 docs

#152 [BE][feat]: 멤버 닉네임 저장 및 조회 기능 구현
  backend/src/main/java/backend/mulkkam/common/exception/errorCode/BadRequestErrorCode.java
  backend/src/main/java/backend/mulkkam/member/controller/MemberController.java
  backend/src/main/java/backend/mulkkam/member/domain/Member.java
  backend/src/main/java/backend/mulkkam/member/domain/vo/MemberNickname.java
  backend/src/main/java/backend/mulkkam/member/dto/request/MemberNicknameModifyRequest.java
  backend/src/main/java/backend/mulkkam/member/dto/request/PhysicalAttributesModifyRequest.java
  backend/src/main/java/backend/mulkkam/member/dto/response/MemberNicknameResponse.java
  backend/src/main/java/backend/mulkkam/member/service/MemberService.java
  backend/src/main/resources/application-local.yml
  backend/src/main/resources/data.sql
  backend/src/test/java/backend/mulkkam/member/domain/vo/MemberNicknameTest.java
  backend/src/test/java/backend/mulkkam/member/service/MemberServiceIntegrationTest.java
  backend/src/test/java/backend/mulkkam/member/service/MemberServiceUnitTest.java
  backend/src/test/resources/application.yml
Labels: BE, 🍯 feat

#137 [BE][feat]: 사용자 컵 삭제
  backend/src/main/java/backend/mulkkam/common/exception/errorCode/BadRequestErrorCode.java
  backend/src/main/java/backend/mulkkam/common/exception/errorCode/NotFoundErrorCode.java
  backend/src/main/java/backend/mulkkam/cup/controller/CupController.java
  backend/src/main/java/backend/mulkkam/cup/domain/Cup.java
  backend/src/main/java/backend/mulkkam/cup/domain/vo/CupRank.java
  backend/src/main/java/backend/mulkkam/cup/repository/CupRepository.java
  backend/src/main/java/backend/mulkkam/cup/service/CupService.java
  backend/src/test/java/backend/mulkkam/cup/domain/vo/CupRankTest.java
  backend/src/test/java/backend/mulkkam/cup/service/CupServiceIntegrationTest.java
  backend/src/test/java/backend/mulkkam/cup/service/CupServiceUnitTest.java
Labels: BE, 🍯 feat

#160 [AN][feat]: TokenRepository 구현
  android/app/src/main/java/com/mulkkam/MulKkamApp.kt
  android/app/src/main/java/com/mulkkam/data/preference/TokenPreference.kt
  android/app/src/main/java/com/mulkkam/data/repository/TokenRepository.kt
  android/app/src/main/java/com/mulkkam/di/PreferenceInjection.kt
  android/app/src/main/java/com/mulkkam/di/RepositoryInjection.kt
Labels: AN, 🍯 feat

#163 [AN][feat]: 메인 액티비티에서 두 번 뒤로가기 클릭시 종료 기능 추가
  android/app/src/main/java/com/mulkkam/ui/main/MainActivity.kt
  android/app/src/main/res/values/strings.xml
Labels: AN, 🍯 feat

#180 [AN][feat]: 홈 프로그레스바 디자인 구현
  android/app/src/main/java/com/mulkkam/ui/custom/GradientDonutChartView.kt
  android/app/src/main/java/com/mulkkam/ui/custom/LinearGradientProgressBarView.kt
  android/app/src/main/java/com/mulkkam/ui/home/HomeFragment.kt
  android/app/src/main/res/layout/fragment_home.xml
  android/app/src/main/res/values/strings.xml
Labels: AN, 🍯 feat

#139 [BE][feat] 닉네임 중복 확인 구현
  backend/src/main/java/backend/mulkkam/common/exception/errorCode/BadRequestErrorCode.java
  backend/src/main/java/backend/mulkkam/common/exception/errorCode/ConflictErrorCode.java
  backend/src/main/java/backend/mulkkam/member/controller/MemberController.java
  backend/src/main/java/backend/mulkkam/member/domain/Member.java
  backend/src/main/java/backend/mulkkam/member/repository/MemberRepository.java
  backend/src/main/java/backend/mulkkam/member/service/MemberService.java
  backend/src/test/java/backend/mulkkam/member/service/MemberServiceIntegrationTest.java
  backend/src/test/java/backend/mulkkam/member/service/MemberServiceUnitTest.java
Labels: BE, 🍯 feat
