Repository woowacourse-teams/2025-mul-kkam, pull requests merged in 2025-08, with the labels that each got.

#214 [AN][refactor]: 기록 화면 요일 문구 UI 수정
  android/app/src/main/java/com/mulkkam/domain/IntakeHistorySummaries.kt
  android/app/src/main/java/com/mulkkam/domain/IntakeHistorySummary.kt
  android/app/src/main/java/com/mulkkam/ui/history/HistoryFragment.kt
  android/app/src/main/java/com/mulkkam/ui/history/HistoryViewModel.kt
  android/app/src/main/res/drawable/bg_common_rectangle_stroke_4dp.xml
  android/app/src/main/res/drawable/ic_history_check.xml
  android/app/src/main/res/drawable/img_history_crying_character.png
  android/app/src/main/res/layout/fragment_history.xml
  android/app/src/main/res/layout/history_water_intake_chart.xml
  android/app/src/main/res/values/strings.xml
Labels: AN, ♻️ refactor

#220 [BE/AN][feat]: 리뷰어, 담당자 자동 배정 CI 추가
  .github/workflows/pr-assign-init.yml
Labels: AN, BE, 🍯 feat

#231 [BE][feat]: 카카오 로그인 구현
  backend/src/main/java/backend/mulkkam/auth/controller/AuthController.java
  backend/src/main/java/backend/mulkkam/auth/domain/OauthAccount.java
  backend/src/main/java/backend/mulkkam/auth/domain/OauthProvider.java
  backend/src/main/java/backend/mulkkam/auth/dto/KakaoSigninRequest.java
  backend/src/main/java/backend/mulkkam/auth/dto/OauthLoginResponse.java
  backend/src/main/java/backend/mulkkam/auth/repository/OauthAccountRepository.java
  backend/src/main/java/backend/mulkkam/auth/service/KakaoAuthService.java
  backend/src/main/java/backend/mulkkam/infrastructure/KakaoRestClient.java
  backend/src/main/java/backend/mulkkam/member/controller/MemberController.java
  backend/src/main/java/backend/mulkkam/member/dto/response/KakaoUserInfo.java
  backend/src/main/resources/data.sql
  backend/src/main/resources/db/migration/V5__add_oauth_account.sql
  backend/src/test/java/backend/mulkkam/intake/repository/IntakeHistoryRepositoryTest.java
Labels: BE, 🍯 feat

#216 [AN][feat]: 스플래쉬 화면 구현
  android/app/build.gradle.kts
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/mulkkam/ui/splash/SplashActivity.kt
  android/app/src/main/res/drawable/bg_splash.xml
  android/app/src/main/res/drawable/img_splash.xml
  android/app/src/main/res/drawable/img_splash_blink.xml
  android/app/src/main/res/layout/activity_splash.xml
  android/app/src/main/res/raw/lottie_splash.json
  android/app/src/main/res/raw/lottie_splash_circle.json
  android/app/src/main/res/raw/lottie_splash_drop.json
  android/app/src/main/res/values/themes.xml
  android/gradle/libs.versions.toml
Labels: AN, 🍯 feat

#240 Feat/221
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/mulkkam/ui/custom/SegmentedProgressBarView.kt
  android/app/src/main/java/com/mulkkam/ui/history/HistoryFragment.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/OnboardingActivity.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/OnboardingStep.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/OnboardingViewModel.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/bioinfo/BioInfoFragment.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/nickname/NicknameFragment.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/targetamount/TargetAmountFragment.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/terms/TermsAgreementUiModel.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/terms/TermsFragment.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/terms/adapter/TermsAdapter.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/terms/adapter/TermsAgreementViewHolder.kt
  android/app/src/main/res/drawable/bg_common_rectangle_stroke_8dp.xml
  android/app/src/main/res/drawable/ic_terms_agreement_check_off.xml
  android/app/src/main/res/drawable/ic_terms_agreement_check_on.xml
  android/app/src/main/res/drawable/ic_terms_agreement_next.xml
  android/app/src/main/res/drawable/ic_terms_all_check_off.xml
  android/app/src/main/res/drawable/ic_terms_all_check_on.xml
  android/app/src/main/res/drawable/selector_terms.xml
  android/app/src/main/res/drawable/selector_terms_agreement.xml
  android/app/src/main/res/layout/activity_onboarding.xml
  android/app/src/main/res/layout/fragment_bio_info.xml
  android/app/src/main/res/layout/fragment_nickname.xml
  android/app/src/main/res/layout/fragment_target_amount.xml
  android/app/src/main/res/layout/fragment_terms.xml
  android/app/src/main/res/layout/item_terms_agreement.xml
  android/app/src/main/res/values/strings.xml
Labels: AN, 🍯 feat

#229 [AN][refactor]: 기록 화면 리사이클러뷰 아이템 마진 수정
  android/app/src/main/java/com/mulkkam/ui/history/adapter/HistoryViewHolder.kt
  android/app/src/main/res/layout/fragment_history.xml
Labels: AN, ♻️ refactor

#179 [BE][feat]: 사용자 컵 랭크 수정
  backend/src/main/java/backend/mulkkam/auth/controller/AuthController.java
  backend/src/main/java/backend/mulkkam/common/exception/errorCode/BadRequestErrorCode.java
  backend/src/main/java/backend/mulkkam/common/exception/errorCode/ConflictErrorCode.java
  backend/src/main/java/backend/mulkkam/cup/controller/CupController.java
  backend/src/main/java/backend/mulkkam/cup/domain/Cup.java
  backend/src/main/java/backend/mulkkam/cup/domain/collection/CupRanks.java
  backend/src/main/java/backend/mulkkam/cup/dto/CupRankDto.java
  backend/src/main/java/backend/mulkkam/cup/dto/request/UpdateCupRanksRequest.java
  backend/src/main/java/backend/mulkkam/cup/dto/response/CupsRanksResponse.java
  backend/src/main/java/backend/mulkkam/cup/service/CupService.java
  backend/src/test/java/backend/mulkkam/cup/domain/collection/CupRanksTest.java
  backend/src/test/java/backend/mulkkam/cup/domain/vo/CupRankTest.java
  backend/src/test/java/backend/mulkkam/cup/service/CupServiceIntegrationTest.java
Labels: BE, 🍯 feat

#242 [BE][feat]: FCM 연동
  .github/workflows/backend-cd.yml
  .github/workflows/backend-ci.yml
  backend/.gitignore
  backend/build.gradle
  backend/src/main/java/backend/mulkkam/MulKkamApplication.java
  backend/src/main/java/backend/mulkkam/common/exception/errorCode/NotFoundErrorCode.java
  backend/src/main/java/backend/mulkkam/common/infrastructure/fcm/FcmController.java
  backend/src/main/java/backend/mulkkam/common/infrastructure/fcm/config/FirebaseConfig.java
  backend/src/main/java/backend/mulkkam/common/infrastructure/fcm/domain/Action.java
  backend/src/main/java/backend/mulkkam/common/infrastructure/fcm/dto/request/SendMessageByFcmTokenRequest.java
  backend/src/main/java/backend/mulkkam/common/infrastructure/fcm/dto/request/SendMessageByFcmTopicRequest.java
  backend/src/main/java/backend/mulkkam/common/infrastructure/fcm/service/FcmService.java
  backend/src/main/java/backend/mulkkam/device/controller/DeviceController.java
  backend/src/main/java/backend/mulkkam/device/domain/Device.java
  backend/src/main/java/backend/mulkkam/device/dto/RegisterDeviceRequest.java
  backend/src/main/java/backend/mulkkam/device/repository/DeviceRepository.java
  backend/src/main/java/backend/mulkkam/device/service/DeviceService.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-local.yml
  backend/src/main/resources/application-test.yml
  backend/src/main/resources/application.yml
  backend/src/main/resources/db/migration/V6__add_device.sql
  backend/src/test/resources/application.yml
Labels: BE, 🍯 feat

#249 [AN][feat]: 온보딩 UI 구현 2
  android/app/src/main/java/com/mulkkam/ui/binding/BindingDialogFragment.kt
  android/app/src/main/java/com/mulkkam/ui/history/HistoryFragment.kt
  android/app/src/main/java/com/mulkkam/ui/home/HomeFragment.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/bioinfo/BioInfoFragment.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/bioinfo/dialog/WeightFragment.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/dialog/CompleteDialogFragment.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/nickname/NicknameFragment.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/targetamount/TargetAmountFragment.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/terms/TermsFragment.kt
  android/app/src/main/java/com/mulkkam/ui/util/StringExtensions.kt
  android/app/src/main/res/drawable/bg_common_rectangle_14dp.xml
  android/app/src/main/res/drawable/ic_bio_info_weight_close.xml
  android/app/src/main/res/drawable/ic_onboarding_complete.gif
  android/app/src/main/res/layout/fragment_bio_info.xml
  android/app/src/main/res/layout/fragment_complete_dialog.xml
  android/app/src/main/res/layout/fragment_weight.xml
  android/app/src/main/res/raw/lottie_confetti.json
  android/app/src/main/res/values/strings.xml
Labels: AN, 🍯 feat

#262 [BE][feat]: 온보딩 API 구현
  backend/src/main/java/backend/mulkkam/auth/domain/OauthAccount.java
  backend/src/main/java/backend/mulkkam/common/exception/errorCode/BadRequestErrorCode.java
  backend/src/main/java/backend/mulkkam/intake/domain/vo/Amount.java
  backend/src/main/java/backend/mulkkam/member/controller/MemberController.java
  backend/src/main/java/backend/mulkkam/member/dto/CreateMemberRequest.java
  backend/src/main/java/backend/mulkkam/member/service/MemberService.java
  backend/src/test/java/backend/mulkkam/auth/domain/OauthAccountTest.java
  backend/src/test/java/backend/mulkkam/intake/domain/vo/AmountTest.java
  backend/src/test/java/backend/mulkkam/intake/service/IntakeAmountServiceIntegrationTest.java
  backend/src/test/java/backend/mulkkam/intake/service/IntakeAmountServiceUnitTest.java
  backend/src/test/java/backend/mulkkam/intake/service/IntakeHistoryServiceIntegrationTest.java
  backend/src/test/java/backend/mulkkam/intake/service/IntakeHistoryServiceUnitTest.java
  backend/src/test/java/backend/mulkkam/member/service/MemberServiceIntegrationTest.java
Labels: BE, 🍯 feat

#261 [AN][feat]: 에러 처리 구현
  android/app/src/main/java/com/mulkkam/data/remote/adapter/MulKkamCallAdapter.kt
  android/app/src/main/java/com/mulkkam/data/remote/adapter/MulKkamCallAdapterFactory.kt
  android/app/src/main/java/com/mulkkam/data/remote/adapter/ResponseCall.kt
  android/app/src/main/java/com/mulkkam/data/remote/model/error/ResponseError.kt
  android/app/src/main/java/com/mulkkam/data/remote/model/response/ErrorResponse.kt
  android/app/src/main/java/com/mulkkam/data/remote/service/AuthService.kt
  android/app/src/main/java/com/mulkkam/data/remote/service/CupsService.kt
  android/app/src/main/java/com/mulkkam/data/remote/service/IntakeService.kt
  android/app/src/main/java/com/mulkkam/data/repository/AuthRepository.kt
  android/app/src/main/java/com/mulkkam/data/repository/AuthRepositoryImpl.kt
  android/app/src/main/java/com/mulkkam/data/repository/CupsRepository.kt
  android/app/src/main/java/com/mulkkam/data/repository/CupsRepositoryImpl.kt
  android/app/src/main/java/com/mulkkam/data/repository/IntakeRepository.kt
  android/app/src/main/java/com/mulkkam/data/repository/IntakeRepositoryImpl.kt
  android/app/src/main/java/com/mulkkam/data/repository/TokenRepository.kt
  android/app/src/main/java/com/mulkkam/data/repository/TokenRepositoryImpl.kt
  android/app/src/main/java/com/mulkkam/di/NetworkInjection.kt
  android/app/src/main/java/com/mulkkam/di/RepositoryInjection.kt
  android/app/src/main/java/com/mulkkam/domain/MulKkamError.kt
  android/app/src/main/java/com/mulkkam/domain/MulKkamResult.kt
  android/app/src/main/java/com/mulkkam/domain/repository/AuthRepository.kt
  android/app/src/main/java/com/mulkkam/domain/repository/CupsRepository.kt
  android/app/src/main/java/com/mulkkam/domain/repository/IntakeRepository.kt
  android/app/src/main/java/com/mulkkam/domain/repository/TokenRepository.kt
  android/app/src/main/java/com/mulkkam/ui/history/HistoryViewModel.kt
  android/app/src/main/java/com/mulkkam/ui/home/HomeViewModel.kt
  android/app/src/main/java/com/mulkkam/ui/login/LoginViewModel.kt
  android/app/src/main/java/com/mulkkam/ui/settinggoal/SettingGoalViewModel.kt
  android/app/src/main/java/com/mulkkam/ui/settingwater/SettingWaterViewModel.kt
  android/app/src/main/java/com/mulkkam/ui/settingwater/dialog/SettingWaterCupViewModel.kt
Labels: AN, 🍯 feat

#266 [AN][feat]: 안드로이드에서 Health Connect 연동
  android/app/build.gradle.kts
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/mulkkam/MulKkamApp.kt
  android/app/src/main/java/com/mulkkam/data/local/.gitkeep
  android/app/src/main/java/com/mulkkam/data/local/service/HealthService.kt
  android/app/src/main/java/com/mulkkam/data/local/work/CalorieSchedulerImpl.kt
  android/app/src/main/java/com/mulkkam/data/local/work/CalorieWorker.kt
  android/app/src/main/java/com/mulkkam/data/local/work/WorkerFactory.kt
  android/app/src/main/java/com/mulkkam/data/repository/HealthRepositoryImpl.kt
  android/app/src/main/java/com/mulkkam/di/HealthConnectInjection.kt
  android/app/src/main/java/com/mulkkam/di/NetworkInjection.kt
  android/app/src/main/java/com/mulkkam/di/RepositoryInjection.kt
  android/app/src/main/java/com/mulkkam/di/ServiceInjection.kt
  android/app/src/main/java/com/mulkkam/di/WorkInjection.kt
  android/app/src/main/java/com/mulkkam/domain/model/CalorieBurn.kt
  android/app/src/main/java/com/mulkkam/domain/repository/HealthRepository.kt
  android/app/src/main/java/com/mulkkam/domain/work/CalorieScheduler.kt
  android/app/src/main/java/com/mulkkam/ui/main/MainActivity.kt
  android/app/src/main/java/com/mulkkam/ui/main/MainViewModel.kt
  android/app/src/main/java/com/mulkkam/ui/settingwater/dialog/SettingWaterCupFragment.kt
  android/app/src/main/java/com/mulkkam/util/extensions/ActivityExtensions.kt
  android/app/src/main/java/com/mulkkam/util/extensions/BundleExtensions.kt
  android/gradle/libs.versions.toml
Labels: AN, 🍯 feat

#271 [AN][feat]: 제정된 안드로이드 로깅 전략 적용
  android/app/build.gradle.kts
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/mulkkam/MulKkamApp.kt
  android/app/src/main/java/com/mulkkam/data/logger/LoggerImpl.kt
  android/app/src/main/java/com/mulkkam/data/remote/interceptor/NetworkLoggingInterceptor.kt
  android/app/src/main/java/com/mulkkam/di/LoggingInjection.kt
  android/app/src/main/java/com/mulkkam/di/NetworkInjection.kt
  android/app/src/main/java/com/mulkkam/domain/logger/Logger.kt
  android/app/src/main/java/com/mulkkam/domain/model/LogEntry.kt
  android/app/src/main/java/com/mulkkam/domain/model/LogEvent.kt
  android/app/src/main/java/com/mulkkam/domain/model/LogLevel.kt
  android/app/src/main/java/com/mulkkam/util/logger/LoggingTree.kt
  android/build.gradle.kts
  android/gradle/libs.versions.toml
Labels: AN, 🍯 feat

#274 [AN][feat]: 온보딩 로직 구현
  android/app/src/main/java/com/mulkkam/ui/onboarding/OnboardingActivity.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/OnboardingInfo.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/OnboardingViewModel.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/bioinfo/BioInfoFragment.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/bioinfo/BioInfoViewModel.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/bioinfo/Gender.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/bioinfo/dialog/WeightFragment.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/nickname/NicknameFragment.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/nickname/NicknameViewModel.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/targetamount/TargetAmountFragment.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/targetamount/TargetAmountViewModel.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/terms/TermsFragment.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/terms/TermsViewModel.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/terms/adapter/TermsAdapter.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/terms/adapter/TermsAgreementHandler.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/terms/adapter/TermsAgreementViewHolder.kt
  android/app/src/main/java/com/mulkkam/ui/util/Event.kt
  android/app/src/main/java/com/mulkkam/ui/util/MutableSingleLiveData.kt
  android/app/src/main/java/com/mulkkam/ui/util/SingleLiveData.kt
  android/app/src/main/res/drawable/selector_onboarding_bio_info.xml
  android/app/src/main/res/layout/fragment_bio_info.xml
  android/app/src/main/res/layout/fragment_nickname.xml
  android/app/src/main/res/layout/fragment_target_amount.xml
  android/app/src/main/res/layout/fragment_terms.xml
  android/app/src/main/res/values/strings.xml
Labels: AN, 🍯 feat

#285 [AN][refactor]: 음용량 조회 응답 수정
  android/app/src/main/java/com/mulkkam/data/remote/model/response/IntakeHistoryResponse.kt
  android/app/src/main/java/com/mulkkam/data/remote/model/response/IntakeHistorySummaryResponse.kt
  android/app/src/main/java/com/mulkkam/data/remote/service/IntakeService.kt
  android/app/src/main/java/com/mulkkam/data/repository/IntakeRepositoryImpl.kt
  android/app/src/main/java/com/mulkkam/domain/IntakeHistory.kt
  android/app/src/main/java/com/mulkkam/domain/repository/IntakeRepository.kt
Labels: AN, ♻️ refactor

#228 [BE][feat]: 날씨 API 를 토대로 날씨를 통한 추가 음용량 제안 기능 구현
  .github/workflows/backend-cd.yml
  backend/src/main/java/backend/mulkkam/common/exception/errorCode/BadRequestErrorCode.java
  backend/src/main/java/backend/mulkkam/intake/domain/vo/ExtraIntakeAmount.java
  backend/src/main/java/backend/mulkkam/intake/dto/OpenWeatherResponse.java
  backend/src/main/java/backend/mulkkam/intake/infrastructure/WeatherRestClient.java
  backend/src/main/java/backend/mulkkam/intake/service/IntakeRecommendedAmountService.java
  backend/src/main/java/backend/mulkkam/intake/service/WeatherClient.java
  backend/src/main/java/backend/mulkkam/intake/service/WeatherService.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-local.yml
  backend/src/main/resources/application-test.yml
  backend/src/test/java/backend/mulkkam/intake/domain/vo/ExtraIntakeAmountTest.java
  backend/src/test/java/backend/mulkkam/intake/service/IntakeRecommendedAmountServiceIntegrationTest.java
  backend/src/test/java/backend/mulkkam/intake/service/WeatherServiceIntegrationTest.java
  backend/src/test/java/backend/mulkkam/intake/service/WeatherServiceUnitTest.java
  backend/src/test/resources/application.yml
Labels: BE, 🍯 feat

#276 [AN][test]: 기록 화면 관련 테스트 구현
  android/app/build.gradle.kts
  android/app/src/androidTest/java/com/mulkkam/ui/history/.gitkeep
  android/app/src/test/java/com/mulkkam/.gitkeep
  android/app/src/test/java/com/mulkkam/ui/fixture/HistoryFixture.kt
  android/app/src/test/java/com/mulkkam/ui/history/HistoryViewModelTest.kt
  android/app/src/test/java/com/mulkkam/ui/util/CoroutinesTestExtension.kt
  android/app/src/test/java/com/mulkkam/ui/util/InstantTaskExecutorExtension.kt
  android/app/src/test/java/com/mulkkam/ui/util/LiveDataExtension.kt
  android/gradle/libs.versions.toml
Labels: AN, 🍯 feat

#246 [BE][feat]: 사용자 음용량 기록 삭제
  backend/src/main/java/backend/mulkkam/common/exception/errorCode/BadRequestErrorCode.java
  backend/src/main/java/backend/mulkkam/common/exception/errorCode/ForbiddenErrorCode.java
  backend/src/main/java/backend/mulkkam/common/exception/errorCode/NotFoundErrorCode.java
  backend/src/main/java/backend/mulkkam/intake/controller/IntakeHistoryController.java
  backend/src/main/java/backend/mulkkam/intake/domain/IntakeHistory.java
  backend/src/main/java/backend/mulkkam/intake/service/IntakeHistoryService.java
  backend/src/test/java/backend/mulkkam/MulKkamApplicationTests.java
  backend/src/test/java/backend/mulkkam/intake/service/IntakeHistoryServiceIntegrationTest.java
Labels: BE, 🍯 feat

#295 [AN][feat]: 홈 화면 플로팅 버튼 구현
  android/app/build.gradle.kts
  android/app/src/main/java/com/mulkkam/data/remote/model/response/CupResponse.kt
  android/app/src/main/java/com/mulkkam/data/remote/model/response/CupsResponse.kt
  android/app/src/main/java/com/mulkkam/data/remote/model/response/IntakeHistoryResultResponse.kt
  android/app/src/main/java/com/mulkkam/data/remote/service/IntakeService.kt
  android/app/src/main/java/com/mulkkam/data/repository/CupsRepositoryImpl.kt
  android/app/src/main/java/com/mulkkam/data/repository/IntakeRepositoryImpl.kt
  android/app/src/main/java/com/mulkkam/domain/IntakeHistorySummary.kt
  android/app/src/main/java/com/mulkkam/domain/model/Cup.kt
  android/app/src/main/java/com/mulkkam/domain/model/Cups.kt
  android/app/src/main/java/com/mulkkam/domain/model/IntakeHistoryResult.kt
  android/app/src/main/java/com/mulkkam/domain/model/IntakeType.kt
  android/app/src/main/java/com/mulkkam/domain/repository/CupsRepository.kt
  android/app/src/main/java/com/mulkkam/domain/repository/IntakeRepository.kt
  android/app/src/main/java/com/mulkkam/ui/custom/ExtendableFloatingActionButton.kt
  android/app/src/main/java/com/mulkkam/ui/custom/ExtendableFloatingMenu.kt
  android/app/src/main/java/com/mulkkam/ui/custom/ExtendableFloatingMenuItem.kt
  android/app/src/main/java/com/mulkkam/ui/home/HomeFragment.kt
  android/app/src/main/java/com/mulkkam/ui/home/HomeViewModel.kt
  android/app/src/main/java/com/mulkkam/ui/settingwater/model/CupUiModel.kt
  android/app/src/main/java/com/mulkkam/ui/settingwater/model/CupsUiModel.kt
  android/app/src/main/java/com/mulkkam/util/extensions/ImageViewExtensions.kt
  android/app/src/main/java/com/mulkkam/util/glide/SvgDecoder.kt
  android/app/src/main/java/com/mulkkam/util/glide/SvgDrawableTranscoder.kt
  android/app/src/main/java/com/mulkkam/util/glide/SvgModule.kt
  android/app/src/main/java/com/mulkkam/util/glide/SvgSoftwareLayerSetter.kt
  android/app/src/main/res/color/selector_custom_expandable_floating_action_button.xml
  android/app/src/main/res/drawable/bg_common_circle_stroke.xml
  android/app/src/main/res/drawable/ic_home_close.xml
  android/app/src/main/res/layout/fragment_home.xml
  android/app/src/main/res/layout/layout_home_floating_action_button.xml
  android/app/src/main/res/layout/layout_home_floating_menu.xml
  android/app/src/main/res/values/strings.xml
  android/build.gradle.kts
  android/gradle/libs.versions.toml
Labels: AN, 🍯 feat

#304 [BE][fix]: 음용량 기록 삭제 기능 수정
  backend/src/main/java/backend/mulkkam/common/exception/errorCode/NotFoundErrorCode.java
  backend/src/main/java/backend/mulkkam/intake/controller/IntakeHistoryController.java
  backend/src/main/java/backend/mulkkam/intake/domain/IntakeHistoryDetail.java
  backend/src/main/java/backend/mulkkam/intake/repository/IntakeHistoryDetailRepository.java
  backend/src/main/java/backend/mulkkam/intake/service/IntakeHistoryService.java
  backend/src/test/java/backend/mulkkam/intake/repository/IntakeHistoryDetailRepositoryTest.java
  backend/src/test/java/backend/mulkkam/intake/service/IntakeHistoryServiceIntegrationTest.java
  backend/src/test/java/backend/mulkkam/intake/service/IntakeHistoryServiceUnitTest.java
  backend/src/test/java/backend/mulkkam/support/IntakeHistoryDetailFixtureBuilder.java
Labels: BE, 🔨 fix

#289 [BE][feat]: 전체 알람 조회 기능 API 구현
  backend/src/main/java/backend/mulkkam/averageTemperature/domain/AverageTemperature.java
  backend/src/main/java/backend/mulkkam/averageTemperature/dto/CreateTokenNotificationRequest.java
  backend/src/main/java/backend/mulkkam/averageTemperature/repository/AverageTemperatureRepository.java
  backend/src/main/java/backend/mulkkam/averageTemperature/serivce/ScheduleService.java
  backend/src/main/java/backend/mulkkam/common/config/SchedulerConfig.java
  backend/src/main/java/backend/mulkkam/common/exception/GlobalExceptionHandler.java
  backend/src/main/java/backend/mulkkam/common/exception/errorCode/BadGateErrorCode.java
  backend/src/main/java/backend/mulkkam/common/exception/errorCode/BadRequestErrorCode.java
  backend/src/main/java/backend/mulkkam/common/exception/errorCode/NotFoundErrorCode.java
  backend/src/main/java/backend/mulkkam/common/infrastructure/fcm/service/FcmService.java
  backend/src/main/java/backend/mulkkam/device/repository/DeviceRepository.java
  backend/src/main/java/backend/mulkkam/intake/dto/OpenWeatherResponse.java
  backend/src/main/java/backend/mulkkam/intake/service/WeatherService.java
  backend/src/main/java/backend/mulkkam/notification/controller/NotificationController.java
  backend/src/main/java/backend/mulkkam/notification/domain/Notification.java
  backend/src/main/java/backend/mulkkam/notification/dto/CreateActivityNotification.java
  backend/src/main/java/backend/mulkkam/notification/dto/CreateTopicNotificationRequest.java
  backend/src/main/java/backend/mulkkam/notification/dto/GetNotificationsRequest.java
  backend/src/main/java/backend/mulkkam/notification/dto/ReadNotificationResponse.java
  backend/src/main/java/backend/mulkkam/notification/dto/ReadNotificationsResponse.java
  backend/src/main/java/backend/mulkkam/notification/repository/NotificationRepository.java
  backend/src/main/java/backend/mulkkam/notification/service/NotificationService.java
  backend/src/main/resources/application-local.yml
  backend/src/main/resources/db/migration/V10__add_average_temperature.sql
  backend/src/main/resources/db/migration/V7__modify_notification_recommended_amount.sql
  backend/src/main/resources/db/migration/V8__separate_intake_history.sql
  backend/src/main/resources/db/migration/V9__add_relationship_notification.sql
  backend/src/test/java/backend/mulkkam/notification/service/NotificationServiceIntegrationTest.java
  backend/src/test/java/backend/mulkkam/notification/service/NotificationServiceUnitTest.java
  backend/src/test/java/backend/mulkkam/support/NotificationFixtureBuilder.java
Labels: BE, 🍯 feat

#290 [AN][feat]: 설정 화면 - 신체 정보 설정 API 연동
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/mulkkam/data/remote/model/request/MembersPhysicalAtrributesRequest.kt
  android/app/src/main/java/com/mulkkam/data/remote/model/response/MembersResponse.kt
  android/app/src/main/java/com/mulkkam/data/remote/service/MembersService.kt
  android/app/src/main/java/com/mulkkam/data/repository/MembersRepositoryImpl.kt
  android/app/src/main/java/com/mulkkam/domain/Gender.kt
  android/app/src/main/java/com/mulkkam/domain/model/MemberInfo.kt
  android/app/src/main/java/com/mulkkam/domain/repository/MembersRepository.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/OnboardingInfo.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/OnboardingViewModel.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/bioinfo/BioInfoFragment.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/bioinfo/BioInfoViewModel.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/bioinfo/Gender.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/bioinfo/dialog/OnboardingWeightFragment.kt
  android/app/src/main/java/com/mulkkam/ui/setting/SettingFragment.kt
  android/app/src/main/java/com/mulkkam/ui/settingbioinfo/SettingBioInfoActivity.kt
  android/app/src/main/java/com/mulkkam/ui/settingbioinfo/SettingBioInfoViewModel.kt
  android/app/src/main/java/com/mulkkam/ui/settingbioinfo/dialog/SettingWeightFragment.kt
  android/app/src/main/res/layout/activity_setting_bio_info.xml
  android/app/src/main/res/layout/fragment_weight.xml
  android/app/src/main/res/values/strings.xml
Labels: AN, 🍯 feat

#309 [AN][feat]: 나의 컵 설정 디자인 및 기능 구현
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/mulkkam/data/remote/model/request/CupRankRequest.kt
  android/app/src/main/java/com/mulkkam/data/remote/model/request/CupsRankRequest.kt
  android/app/src/main/java/com/mulkkam/data/remote/model/response/CupRankResponse.kt
  android/app/src/main/java/com/mulkkam/data/remote/model/response/CupResponse.kt
  android/app/src/main/java/com/mulkkam/data/remote/model/response/CupsRankResponse.kt
  android/app/src/main/java/com/mulkkam/data/remote/model/response/CupsResponse.kt
  android/app/src/main/java/com/mulkkam/data/remote/service/CupsService.kt
  android/app/src/main/java/com/mulkkam/data/repository/CupsRepositoryImpl.kt
  android/app/src/main/java/com/mulkkam/domain/logger/Logger.kt
  android/app/src/main/java/com/mulkkam/domain/model/Cup.kt
  android/app/src/main/java/com/mulkkam/domain/model/Cups.kt
  android/app/src/main/java/com/mulkkam/domain/repository/CupsRepository.kt
  android/app/src/main/java/com/mulkkam/ui/history/HistoryFragment.kt
  android/app/src/main/java/com/mulkkam/ui/home/HomeViewModel.kt
  android/app/src/main/java/com/mulkkam/ui/main/MainActivity.kt
  android/app/src/main/java/com/mulkkam/ui/setting/SettingFragment.kt
  android/app/src/main/java/com/mulkkam/ui/settingcups/SettingCupsActivity.kt
  android/app/src/main/java/com/mulkkam/ui/settingcups/SettingCupsViewModel.kt
  android/app/src/main/java/com/mulkkam/ui/settingcups/adapter/AddViewHolder.kt
  android/app/src/main/java/com/mulkkam/ui/settingcups/adapter/CupViewHolder.kt
  android/app/src/main/java/com/mulkkam/ui/settingcups/adapter/CupsItemTouchHelperCallback.kt
  android/app/src/main/java/com/mulkkam/ui/settingcups/adapter/ItemReorderListener.kt
  android/app/src/main/java/com/mulkkam/ui/settingcups/adapter/SettingCupsAdapter.kt
  android/app/src/main/java/com/mulkkam/ui/settingcups/adapter/SettingCupsDiffCallback.kt
  android/app/src/main/java/com/mulkkam/ui/settingcups/adapter/SettingCupsItem.kt
  android/app/src/main/java/com/mulkkam/ui/settingcups/adapter/SettingCupsViewHolder.kt
  android/app/src/main/java/com/mulkkam/ui/settingcups/adapter/SettingCupsViewType.kt
  android/app/src/main/java/com/mulkkam/ui/settingcups/dialog/SettingCupFragment.kt
  android/app/src/main/java/com/mulkkam/ui/settingcups/dialog/SettingCupViewModel.kt
  android/app/src/main/java/com/mulkkam/ui/settingcups/model/CupUiModel.kt
  android/app/src/main/java/com/mulkkam/ui/settingcups/model/CupsUiModel.kt
  android/app/src/main/java/com/mulkkam/ui/settingcups/model/SettingWaterCupEditType.kt
  android/app/src/main/java/com/mulkkam/ui/settingwater/SettingWaterActivity.kt
  android/app/src/main/java/com/mulkkam/ui/settingwater/SettingWaterViewModel.kt
  android/app/src/main/java/com/mulkkam/ui/settingwater/adapter/CupViewHolder.kt
  android/app/src/main/java/com/mulkkam/ui/settingwater/adapter/SettingWaterAdapter.kt
  android/app/src/main/java/com/mulkkam/ui/settingwater/adapter/SettingWaterDiffCallback.kt
  android/app/src/main/java/com/mulkkam/ui/settingwater/adapter/SettingWaterItem.kt
  android/app/src/main/java/com/mulkkam/ui/settingwater/adapter/SettingWaterViewType.kt
  android/app/src/main/res/drawable/bg_common_rectangle_12dp.xml
  android/app/src/main/res/drawable/btn_setting_cup_move.xml
  android/app/src/main/res/drawable/btn_setting_cups_edit.xml
  android/app/src/main/res/drawable/ic_setting_cup_handle.xml
  android/app/src/main/res/drawable/ic_setting_cups_add.xml
  android/app/src/main/res/layout/activity_setting_cups.xml
  android/app/src/main/res/layout/fragment_history.xml
  android/app/src/main/res/layout/fragment_setting_cup.xml
  android/app/src/main/res/layout/fragment_weight.xml
  android/app/src/main/res/layout/item_setting_cups_add.xml
  android/app/src/main/res/layout/item_setting_cups_cup.xml
  android/app/src/main/res/layout/item_setting_water_cup.xml
  android/app/src/main/res/layout/layout_history_water_intake_chart.xml
  android/app/src/main/res/values/strings.xml
Labels: AN, 🍯 feat

#310 [AN][feat]: 설정화면 - 사용자 신체 속성으로 추천 목표 음용량 반환 API 연결
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/mulkkam/data/remote/service/IntakeService.kt
  android/app/src/main/java/com/mulkkam/data/repository/IntakeRepositoryImpl.kt
  android/app/src/main/java/com/mulkkam/domain/MulKkamError.kt
  android/app/src/main/java/com/mulkkam/domain/model/TargetAmount.kt
  android/app/src/main/java/com/mulkkam/domain/repository/IntakeRepository.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/targetamount/TargetAmountFragment.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/targetamount/TargetAmountViewModel.kt
  android/app/src/main/java/com/mulkkam/ui/setting/SettingFragment.kt
  android/app/src/main/java/com/mulkkam/ui/settinggoal/SettingGoalActivity.kt
  android/app/src/main/java/com/mulkkam/ui/settinggoal/SettingGoalViewModel.kt
  android/app/src/main/java/com/mulkkam/ui/settingtargetamount/SettingTargetAmountActivity.kt
  android/app/src/main/java/com/mulkkam/ui/settingtargetamount/SettingTargetAmountViewModel.kt
  android/app/src/main/java/com/mulkkam/ui/util/StringExtensions.kt
  android/app/src/main/res/drawable/selector_common_button_enabled.xml
  android/app/src/main/res/layout/activity_setting_target_amount.xml
  android/app/src/main/res/layout/fragment_setting_cup.xml
  android/app/src/main/res/layout/fragment_target_amount.xml
  android/app/src/main/res/values/strings.xml
Labels: AN, 🍯 feat

#267 [BE][feat]: 온보딩 여부 확인 기능 구현
  backend/src/main/java/backend/mulkkam/auth/domain/OauthAccount.java
  backend/src/main/java/backend/mulkkam/auth/dto/OauthLoginResponse.java
  backend/src/main/java/backend/mulkkam/auth/repository/OauthAccountRepository.java
  backend/src/main/java/backend/mulkkam/auth/service/KakaoAuthService.java
  backend/src/main/java/backend/mulkkam/common/config/WebConfiguration.java
  backend/src/main/java/backend/mulkkam/common/resolver/MemberResolver.java
  backend/src/main/java/backend/mulkkam/common/resolver/OauthAccountResolver.java
  backend/src/main/java/backend/mulkkam/cup/controller/CupController.java
  backend/src/main/java/backend/mulkkam/cup/repository/CupRepository.java
  backend/src/main/java/backend/mulkkam/cup/service/CupService.java
  backend/src/main/java/backend/mulkkam/device/controller/DeviceController.java
  backend/src/main/java/backend/mulkkam/device/service/DeviceService.java
  backend/src/main/java/backend/mulkkam/intake/controller/IntakeAmountController.java
  backend/src/main/java/backend/mulkkam/intake/controller/IntakeHistoryController.java
  backend/src/main/java/backend/mulkkam/intake/repository/IntakeHistoryDetailRepository.java
  backend/src/main/java/backend/mulkkam/intake/repository/IntakeHistoryRepository.java
  backend/src/main/java/backend/mulkkam/intake/service/IntakeAmountService.java
  backend/src/main/java/backend/mulkkam/intake/service/IntakeHistoryService.java
  backend/src/main/java/backend/mulkkam/member/controller/MemberController.java
  backend/src/main/java/backend/mulkkam/member/domain/Member.java
  backend/src/main/java/backend/mulkkam/member/dto/CreateMemberRequest.java
  backend/src/main/java/backend/mulkkam/member/dto/OnboardingStatusResponse.java
  backend/src/main/java/backend/mulkkam/member/service/MemberService.java
  backend/src/main/java/backend/mulkkam/notification/controller/NotificationController.java
  backend/src/main/java/backend/mulkkam/notification/service/NotificationService.java
  backend/src/main/resources/data.sql
  backend/src/main/resources/db/migration/V10__add_marketing_column.sql
  backend/src/test/java/backend/mulkkam/common/resolver/MemberResolverTest.java
  backend/src/test/java/backend/mulkkam/common/resolver/OauthAccountResolverTest.java
  backend/src/test/java/backend/mulkkam/cup/repository/CupRepositoryTest.java
  backend/src/test/java/backend/mulkkam/cup/service/CupServiceIntegrationTest.java
  backend/src/test/java/backend/mulkkam/cup/service/CupServiceUnitTest.java
  backend/src/test/java/backend/mulkkam/intake/repository/IntakeHistoryDetailRepositoryTest.java
  backend/src/test/java/backend/mulkkam/intake/service/IntakeAmountServiceIntegrationTest.java
  backend/src/test/java/backend/mulkkam/intake/service/IntakeAmountServiceUnitTest.java
  backend/src/test/java/backend/mulkkam/intake/service/IntakeHistoryServiceIntegrationTest.java
  backend/src/test/java/backend/mulkkam/intake/service/IntakeHistoryServiceUnitTest.java
  backend/src/test/java/backend/mulkkam/member/controller/MemberControllerTest.java
  backend/src/test/java/backend/mulkkam/member/service/MemberServiceIntegrationTest.java
  backend/src/test/java/backend/mulkkam/member/service/MemberServiceUnitTest.java
  backend/src/test/java/backend/mulkkam/notification/service/NotificationServiceIntegrationTest.java
  backend/src/test/java/backend/mulkkam/notification/service/NotificationServiceUnitTest.java
  backend/src/test/java/backend/mulkkam/support/CupFixtureBuilder.java
  backend/src/test/java/backend/mulkkam/support/MemberFixtureBuilder.java
Labels: BE, 🍯 feat

#256 [BE][feat]: 스냅샷 저장 및 조회 로직 구현
  backend/src/main/java/backend/mulkkam/common/exception/errorCode/NotFoundErrorCode.java
  backend/src/main/java/backend/mulkkam/intake/domain/TargetAmountSnapshot.java
  backend/src/main/java/backend/mulkkam/intake/dto/request/DateRangeRequest.java
  backend/src/main/java/backend/mulkkam/intake/dto/response/IntakeHistorySummaryResponse.java
  backend/src/main/java/backend/mulkkam/intake/repository/TargetAmountSnapshotRepository.java
  backend/src/main/java/backend/mulkkam/intake/service/IntakeAmountService.java
  backend/src/main/java/backend/mulkkam/intake/service/IntakeHistoryService.java
  backend/src/main/java/backend/mulkkam/member/controller/MemberController.java
  backend/src/test/java/backend/mulkkam/intake/repository/TargetAmountSnapshotRepositoryTest.java
  backend/src/test/java/backend/mulkkam/intake/service/IntakeAmountServiceIntegrationTest.java
  backend/src/test/java/backend/mulkkam/intake/service/IntakeAmountServiceUnitTest.java
  backend/src/test/java/backend/mulkkam/intake/service/IntakeHistoryServiceIntegrationTest.java
  backend/src/test/java/backend/mulkkam/intake/service/IntakeHistoryServiceUnitTest.java
  backend/src/test/java/backend/mulkkam/support/TargetAmountSnapshotFixtureBuilder.java
Labels: BE, 🍯 feat

#325 [AN][feat]: 스플래시 토큰 확인 로직 구현
  android/app/src/main/java/com/mulkkam/data/remote/model/response/AuthResponse.kt
  android/app/src/main/java/com/mulkkam/ui/login/LoginActivity.kt
  android/app/src/main/java/com/mulkkam/ui/model/AppAuthState.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/OnboardingActivity.kt
  android/app/src/main/java/com/mulkkam/ui/splash/SplashActivity.kt
  android/app/src/main/java/com/mulkkam/ui/splash/SplashViewModel.kt
Labels: AN, 🍯 feat

#303 [BE][fix]: 사용자 목표 음용량 변경 시 금일 기록의 목표도 바뀌도록 버그 수정
  backend/src/main/java/backend/mulkkam/intake/domain/IntakeHistory.java
  backend/src/main/java/backend/mulkkam/intake/service/IntakeAmountService.java
  backend/src/test/java/backend/mulkkam/intake/service/IntakeAmountServiceIntegrationTest.java
  backend/src/test/java/backend/mulkkam/intake/service/IntakeAmountServiceUnitTest.java
Labels: BE, 🔨 fix

#288 [BE][feat]: 사용자 금일 진행 상태 정보 조회
  backend/src/main/java/backend/mulkkam/intake/repository/IntakeHistoryRepository.java
  backend/src/main/java/backend/mulkkam/member/controller/MemberController.java
  backend/src/main/java/backend/mulkkam/member/dto/response/ProgressInfoResponse.java
  backend/src/main/java/backend/mulkkam/member/service/MemberService.java
  backend/src/test/java/backend/mulkkam/common/filter/JwtAuthenticationFilterTest.java
  backend/src/test/java/backend/mulkkam/intake/repository/IntakeHistoryRepositoryTest.java
  backend/src/test/java/backend/mulkkam/intake/service/IntakeHistoryServiceIntegrationTest.java
  backend/src/test/java/backend/mulkkam/member/service/MemberServiceIntegrationTest.java
  backend/src/test/java/backend/mulkkam/member/service/MemberServiceUnitTest.java
Labels: BE, 🍯 feat

#328 [AN][feat]: 스플래시/로그인 온보딩 여부 확인 API 연결
  android/app/src/main/java/com/mulkkam/data/remote/model/response/MembersCheckOnboardingResponse.kt
  android/app/src/main/java/com/mulkkam/data/remote/service/MembersService.kt
  android/app/src/main/java/com/mulkkam/data/repository/MembersRepositoryImpl.kt
  android/app/src/main/java/com/mulkkam/domain/repository/MembersRepository.kt
  android/app/src/main/java/com/mulkkam/ui/login/LoginActivity.kt
  android/app/src/main/java/com/mulkkam/ui/login/LoginViewModel.kt
  android/app/src/main/java/com/mulkkam/ui/splash/SplashActivity.kt
  android/app/src/main/java/com/mulkkam/ui/splash/SplashViewModel.kt
Labels: AN, 🍯 feat

#321 [AN][refactor]: 온보딩 완료 다이얼로그 디자인 수정
  android/app/src/main/java/com/mulkkam/ui/onboarding/dialog/CompleteDialogFragment.kt
  android/app/src/main/res/drawable/bg_common_rectangle_14dp.xml
  android/app/src/main/res/layout/fragment_complete_dialog.xml
Labels: AN, ♻️ refactor

#361 [AN][feat]: 홈화면 알림 권한 요청 기능 추가
  android/app/src/main/java/com/mulkkam/ui/main/MainActivity.kt
  android/app/src/main/res/values/strings.xml
Labels: AN, 🍯 feat

#348 [AN][feat]: 홈 화면 당일 기록 API 요청
  android/app/src/main/java/com/mulkkam/data/remote/model/response/MembersProgressInfoResponse.kt
  android/app/src/main/java/com/mulkkam/data/remote/service/MembersService.kt
  android/app/src/main/java/com/mulkkam/data/repository/MembersRepositoryImpl.kt
  android/app/src/main/java/com/mulkkam/domain/IntakeHistorySummary.kt
  android/app/src/main/java/com/mulkkam/domain/model/TodayProgressInfo.kt
  android/app/src/main/java/com/mulkkam/domain/repository/MembersRepository.kt
  android/app/src/main/java/com/mulkkam/ui/home/HomeFragment.kt
  android/app/src/main/java/com/mulkkam/ui/home/HomeViewModel.kt
  android/app/src/main/java/com/mulkkam/ui/settingtargetamount/SettingTargetAmountActivity.kt
  android/app/src/main/res/layout/activity_login.xml
  android/app/src/main/res/layout/fragment_home.xml
  android/app/src/main/res/values/strings.xml
Labels: AN, 🍯 feat

#360 [AN][feat]: 기록 화면 상세내역 삭제 API 연결
  android/app/src/main/java/com/mulkkam/data/remote/model/response/IntakeHistoryDetailsResponse.kt
  android/app/src/main/java/com/mulkkam/data/remote/model/response/MemberNickname.kt
  android/app/src/main/java/com/mulkkam/data/remote/model/response/PhysicalAttributes.kt
  android/app/src/main/java/com/mulkkam/data/remote/model/response/TargetAmount.kt
  android/app/src/main/java/com/mulkkam/data/remote/service/IntakeService.kt
  android/app/src/main/java/com/mulkkam/data/repository/IntakeRepositoryImpl.kt
  android/app/src/main/java/com/mulkkam/domain/repository/IntakeRepository.kt
  android/app/src/main/java/com/mulkkam/ui/history/HistoryFragment.kt
  android/app/src/main/java/com/mulkkam/ui/history/HistoryViewModel.kt
Labels: AN, 🍯 feat

#368 [AN][feat]: 알림 화면 API 연결
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/mulkkam/data/remote/model/error/ResponseError.kt
  android/app/src/main/java/com/mulkkam/data/remote/model/response/IntakeHistoryResponse.kt
  android/app/src/main/java/com/mulkkam/data/remote/model/response/IntakeHistorySummaryResponse.kt
  android/app/src/main/java/com/mulkkam/data/remote/model/response/MembersResponse.kt
  android/app/src/main/java/com/mulkkam/data/remote/model/response/NotificationsResponse.kt
  android/app/src/main/java/com/mulkkam/data/remote/service/IntakeService.kt
  android/app/src/main/java/com/mulkkam/data/remote/service/NotificationService.kt
  android/app/src/main/java/com/mulkkam/data/remote/service/NotificationsService.kt
  android/app/src/main/java/com/mulkkam/data/repository/AuthRepositoryImpl.kt
  android/app/src/main/java/com/mulkkam/data/repository/CupsRepositoryImpl.kt
  android/app/src/main/java/com/mulkkam/data/repository/DevicesRepositoryImpl.kt
  android/app/src/main/java/com/mulkkam/data/repository/IntakeRepositoryImpl.kt
  android/app/src/main/java/com/mulkkam/data/repository/MembersRepositoryImpl.kt
  android/app/src/main/java/com/mulkkam/data/repository/NicknameRepositoryImpl.kt
  android/app/src/main/java/com/mulkkam/data/repository/NotificationRepositoryImpl.kt
  android/app/src/main/java/com/mulkkam/data/repository/TokenRepositoryImpl.kt
  android/app/src/main/java/com/mulkkam/di/ServiceInjection.kt
  android/app/src/main/java/com/mulkkam/domain/model/Gender.kt
  android/app/src/main/java/com/mulkkam/domain/model/IntakeHistory.kt
  android/app/src/main/java/com/mulkkam/domain/model/IntakeHistorySummaries.kt
  android/app/src/main/java/com/mulkkam/domain/model/IntakeHistorySummary.kt
  android/app/src/main/java/com/mulkkam/domain/model/MemberInfo.kt
  android/app/src/main/java/com/mulkkam/domain/model/MulKkamError.kt
  android/app/src/main/java/com/mulkkam/domain/model/MulKkamResult.kt
  android/app/src/main/java/com/mulkkam/domain/model/Notification.kt
  android/app/src/main/java/com/mulkkam/domain/model/NotificationType.kt
  android/app/src/main/java/com/mulkkam/domain/model/OnboardingInfo.kt
  android/app/src/main/java/com/mulkkam/domain/model/TargetAmount.kt
  android/app/src/main/java/com/mulkkam/domain/repository/AuthRepository.kt
  android/app/src/main/java/com/mulkkam/domain/repository/CupsRepository.kt
  android/app/src/main/java/com/mulkkam/domain/repository/DevicesRepository.kt
  android/app/src/main/java/com/mulkkam/domain/repository/IntakeRepository.kt
  android/app/src/main/java/com/mulkkam/domain/repository/MembersRepository.kt
  android/app/src/main/java/com/mulkkam/domain/repository/NicknameRepository.kt
  android/app/src/main/java/com/mulkkam/domain/repository/NotificationRepository.kt
  android/app/src/main/java/com/mulkkam/domain/repository/TokenRepository.kt
  android/app/src/main/java/com/mulkkam/ui/history/HistoryFragment.kt
  android/app/src/main/java/com/mulkkam/ui/history/HistoryViewModel.kt
  android/app/src/main/java/com/mulkkam/ui/history/adapter/HistoryAdapter.kt
  android/app/src/main/java/com/mulkkam/ui/history/adapter/HistoryViewHolder.kt
  android/app/src/main/java/com/mulkkam/ui/home/HomeFragment.kt
  android/app/src/main/java/com/mulkkam/ui/login/LoginActivity.kt
  android/app/src/main/java/com/mulkkam/ui/notification/NotificationActivity.kt
  android/app/src/main/java/com/mulkkam/ui/notification/NotificationViewModel.kt
  android/app/src/main/java/com/mulkkam/ui/notification/adapter/NotificationAdapter.kt
  android/app/src/main/java/com/mulkkam/ui/notification/adapter/NotificationViewHolder.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/OnboardingViewModel.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/bioinfo/BioInfoFragment.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/bioinfo/BioInfoViewModel.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/targetamount/TargetAmountViewModel.kt
  android/app/src/main/java/com/mulkkam/ui/settingbioinfo/SettingBioInfoActivity.kt
  android/app/src/main/java/com/mulkkam/ui/settingbioinfo/SettingBioInfoViewModel.kt
  android/app/src/main/res/drawable/selector_notification_item_background.xml
  android/app/src/main/res/layout/activity_notification.xml
  android/app/src/main/res/layout/fragment_history.xml
  android/app/src/main/res/layout/item_home_notification.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/test/java/com/mulkkam/ui/fixture/HistoryFixture.kt
  android/app/src/test/java/com/mulkkam/ui/history/HistoryViewModelTest.kt
Labels: AN, 🍯 feat

#377 [AN][refactor]: 로깅 보안 및 의존성 보완
  android/app/src/main/java/com/mulkkam/MulKkamApp.kt
  android/app/src/main/java/com/mulkkam/data/logger/LoggerImpl.kt
  android/app/src/main/java/com/mulkkam/data/logger/SensitiveInfoSanitizerImpl.kt
  android/app/src/main/java/com/mulkkam/di/LoggingInjection.kt
  android/app/src/main/java/com/mulkkam/di/NetworkInjection.kt
  android/app/src/main/java/com/mulkkam/di/ServiceInjection.kt
  android/app/src/main/java/com/mulkkam/domain/logger/Logger.kt
  android/app/src/main/java/com/mulkkam/domain/logger/SensitiveInfoSanitizer.kt
  android/app/src/main/java/com/mulkkam/ui/settingbioinfo/SettingBioInfoActivity.kt
  android/app/src/main/java/com/mulkkam/util/logger/DebugLoggingTree.kt
  android/app/src/main/java/com/mulkkam/util/logger/ReleaseLoggingTree.kt
Labels: AN, ♻️ refactor

#388 [AN][feat]: 섭취 성공시 SnackBar 출력
  android/app/src/main/java/com/mulkkam/ui/home/HomeFragment.kt
  android/app/src/main/java/com/mulkkam/ui/home/HomeViewModel.kt
  android/app/src/main/java/com/mulkkam/ui/home/dialog/ManualDrinkFragment.kt
  android/app/src/main/res/values/strings.xml
Labels: AN, 🍯 feat

#392 [AN][refactor]: 온보딩 텍스트 클릭해도 약관 동의 체크되게 (피그마 반영)
  android/app/src/main/java/com/mulkkam/ui/onboarding/terms/TermsFragment.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/terms/TermsViewModel.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/terms/adapter/TermsAdapter.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/terms/adapter/TermsAgreementHandler.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/terms/adapter/TermsAgreementViewHolder.kt
  android/app/src/main/res/layout/fragment_terms.xml
  android/app/src/main/res/layout/item_terms_agreement.xml
Labels: AN, ♻️ refactor

#394 [AN][refactor]: 스플래시 인증 실패시 로그인 화면으로 이동
  android/app/src/main/java/com/mulkkam/ui/splash/SplashViewModel.kt
Labels: AN, ♻️ refactor

#410 [AN][style]: 모든 뷰 하단 버튼 크기 및 플로팅 조정
  android/app/src/main/java/com/mulkkam/ui/custom/ExtendableFloatingMenu.kt
  android/app/src/main/java/com/mulkkam/ui/history/HistoryFragment.kt
  android/app/src/main/java/com/mulkkam/ui/home/HomeFragment.kt
  android/app/src/main/java/com/mulkkam/ui/login/LoginActivity.kt
  android/app/src/main/java/com/mulkkam/ui/main/MainActivity.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/bioinfo/BioInfoFragment.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/dialog/CompleteDialogFragment.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/nickname/NicknameFragment.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/targetamount/TargetAmountFragment.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/terms/TermsFragment.kt
  android/app/src/main/java/com/mulkkam/ui/settingbioinfo/SettingBioInfoActivity.kt
  android/app/src/main/java/com/mulkkam/ui/settingcups/adapter/CupViewHolder.kt
  android/app/src/main/java/com/mulkkam/ui/settingnickname/SettingNicknameActivity.kt
  android/app/src/main/java/com/mulkkam/ui/settingtargetamount/SettingTargetAmountActivity.kt
  android/app/src/main/java/com/mulkkam/ui/util/extensions/ActivityExtensions.kt
  android/app/src/main/java/com/mulkkam/ui/util/extensions/ImageViewExtensions.kt
  android/app/src/main/java/com/mulkkam/ui/util/extensions/StringExtensions.kt
  android/app/src/main/java/com/mulkkam/ui/util/extensions/ViewExtensions.kt
  android/app/src/main/java/com/mulkkam/ui/util/glide/SvgDecoder.kt
  android/app/src/main/java/com/mulkkam/ui/util/glide/SvgDrawableTranscoder.kt
  android/app/src/main/java/com/mulkkam/ui/util/glide/SvgModule.kt
  android/app/src/main/java/com/mulkkam/ui/util/glide/SvgSoftwareLayerSetter.kt
  android/app/src/main/res/color/selector_save_background.xml
  android/app/src/main/res/layout/activity_setting_bio_info.xml
  android/app/src/main/res/layout/activity_setting_nickname.xml
  android/app/src/main/res/layout/activity_setting_target_amount.xml
  android/app/src/main/res/layout/fragment_bio_info.xml
  android/app/src/main/res/layout/fragment_complete_dialog.xml
  android/app/src/main/res/layout/fragment_delete_confirm_dialog.xml
  android/app/src/main/res/layout/fragment_manual_drink.xml
  android/app/src/main/res/layout/fragment_nickname.xml
  android/app/src/main/res/layout/fragment_setting_cup.xml
  android/app/src/main/res/layout/fragment_target_amount.xml
  android/app/src/main/res/layout/fragment_terms.xml
  android/app/src/main/res/layout/fragment_weight.xml
  android/app/src/main/res/layout/item_setting_cups_add.xml
  android/app/src/main/res/layout/layout_mulkkam_chip.xml
  android/app/src/main/res/values/strings.xml
Labels: AN, 🎨 style

#402 [AN][feat]: 홈 플로팅 버튼에 컵 용량 추가
  android/app/src/main/java/com/mulkkam/ui/custom/ExtendableFloatingActionButton.kt
  android/app/src/main/java/com/mulkkam/ui/custom/ExtendableFloatingMenu.kt
  android/app/src/main/java/com/mulkkam/ui/custom/ExtendableFloatingMenuItem.kt
  android/app/src/main/java/com/mulkkam/ui/home/HomeFragment.kt
  android/app/src/main/res/layout/layout_expandable_floating_menu.xml
  android/app/src/main/res/values/strings.xml
Labels: AN, 🍯 feat

#404 [AN][refactor]: 로깅 내부 로직 리팩터링
  android/app/src/main/java/com/mulkkam/data/logger/LoggerImpl.kt
  android/app/src/main/java/com/mulkkam/di/LoggingInjection.kt
  android/app/src/main/java/com/mulkkam/di/NetworkInjection.kt
Labels: AN, ♻️ refactor

#413 [AN][refactor]: 몸무게 도메인 모델로 설정
  .github/workflows/pr-assign-init.yml
  android/app/src/main/java/com/mulkkam/data/remote/model/request/MembersRequest.kt
  android/app/src/main/java/com/mulkkam/data/remote/model/response/MembersResponse.kt
  android/app/src/main/java/com/mulkkam/data/repository/IntakeRepositoryImpl.kt
  android/app/src/main/java/com/mulkkam/data/repository/MembersRepositoryImpl.kt
  android/app/src/main/java/com/mulkkam/domain/model/BioWeight.kt
  android/app/src/main/java/com/mulkkam/domain/model/MemberInfo.kt
  android/app/src/main/java/com/mulkkam/domain/model/OnboardingInfo.kt
  android/app/src/main/java/com/mulkkam/domain/repository/IntakeRepository.kt
  android/app/src/main/java/com/mulkkam/domain/repository/MembersRepository.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/OnboardingViewModel.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/bioinfo/BioInfoFragment.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/bioinfo/BioInfoViewModel.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/bioinfo/dialog/OnboardingWeightFragment.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/targetamount/TargetAmountViewModel.kt
  android/app/src/main/java/com/mulkkam/ui/settingbioinfo/SettingBioInfoActivity.kt
  android/app/src/main/java/com/mulkkam/ui/settingbioinfo/SettingBioInfoViewModel.kt
  android/app/src/main/java/com/mulkkam/ui/settingbioinfo/dialog/SettingWeightFragment.kt
Labels: AN, ♻️ refactor

#399 [BE][chore] 액츄에이터 포트 변경
  backend/src/main/java/backend/mulkkam/common/filter/JwtAuthenticationFilter.java
  backend/src/main/resources/application.yml
Labels: BE, 🚧 chore

#397 [AN][feat]: 버튼 여러번 클릭 방지 확장함수
  android/app/src/main/java/com/mulkkam/ui/custom/ExtendableFloatingActionButton.kt
  android/app/src/main/java/com/mulkkam/ui/history/HistoryFragment.kt
  android/app/src/main/java/com/mulkkam/ui/history/dialog/DeleteConfirmDialogFragment.kt
  android/app/src/main/java/com/mulkkam/ui/home/HomeFragment.kt
  android/app/src/main/java/com/mulkkam/ui/home/dialog/ManualDrinkFragment.kt
  android/app/src/main/java/com/mulkkam/ui/login/LoginActivity.kt
  android/app/src/main/java/com/mulkkam/ui/notification/NotificationActivity.kt
  android/app/src/main/java/com/mulkkam/ui/notification/adapter/NotificationViewHolder.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/OnboardingActivity.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/bioinfo/BioInfoFragment.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/bioinfo/dialog/OnboardingWeightFragment.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/dialog/CompleteDialogFragment.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/nickname/NicknameFragment.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/targetamount/TargetAmountFragment.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/terms/TermsFragment.kt
  android/app/src/main/java/com/mulkkam/ui/setting/adapter/NormalViewHolder.kt
  android/app/src/main/java/com/mulkkam/ui/settingbioinfo/SettingBioInfoActivity.kt
  android/app/src/main/java/com/mulkkam/ui/settingbioinfo/dialog/SettingWeightFragment.kt
  android/app/src/main/java/com/mulkkam/ui/settingcups/SettingCupsActivity.kt
  android/app/src/main/java/com/mulkkam/ui/settingcups/adapter/AddViewHolder.kt
  android/app/src/main/java/com/mulkkam/ui/settingcups/adapter/CupViewHolder.kt
  android/app/src/main/java/com/mulkkam/ui/settingcups/dialog/SettingCupFragment.kt
  android/app/src/main/java/com/mulkkam/ui/settingnickname/SettingNicknameActivity.kt
  android/app/src/main/java/com/mulkkam/ui/settingtargetamount/SettingTargetAmountActivity.kt
  android/app/src/main/java/com/mulkkam/ui/util/extensions/ViewExtensions.kt
Labels: AN, 🍯 feat

#416 [BE][chore]: actuator 수집 메트릭 관련 경로 설정
  backend/build.gradle
  backend/src/main/java/backend/mulkkam/common/config/MetricConfiguration.java
  backend/src/main/resources/application.yml
Labels: BE, 🚧 chore

#390 [AN][refactor]: 기록 화면에서 미래/과거 화면 UI 수정
  android/app/src/main/java/com/mulkkam/domain/model/IntakeHistorySummary.kt
  android/app/src/main/java/com/mulkkam/domain/model/WaterIntakeState.kt
  android/app/src/main/java/com/mulkkam/ui/history/HistoryFragment.kt
  android/app/src/main/java/com/mulkkam/ui/history/HistoryViewModel.kt
  android/app/src/test/java/com/mulkkam/ui/fixture/HistoryFixture.kt
  android/app/src/test/java/com/mulkkam/ui/history/HistoryViewModelTest.kt
Labels: AN, ♻️ refactor

#424 [BE][feat]: 로그백 설정
  .github/workflows/backend-cd.yml
  backend/src/main/java/backend/mulkkam/common/exception/GlobalExceptionHandler.java
  backend/src/main/java/backend/mulkkam/common/filter/ApiPerformanceInterceptor.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-local.yml
  backend/src/main/resources/logback-spring.xml
Labels: BE, 🍯 feat

#414 [AN][feat]: 모든 editText imeOptions 기능 구현, editText maxLines 제한
  android/app/src/main/res/layout/activity_setting_nickname.xml
  android/app/src/main/res/layout/activity_setting_target_amount.xml
  android/app/src/main/res/layout/fragment_manual_drink.xml
  android/app/src/main/res/layout/fragment_nickname.xml
  android/app/src/main/res/layout/fragment_setting_cup.xml
  android/app/src/main/res/layout/fragment_target_amount.xml
Labels: AN, ♻️ refactor

#423 [AN][test]: HistoryViewModel 테스트 코드 작성
  android/app/src/main/java/com/mulkkam/ui/history/HistoryViewModel.kt
  android/app/src/test/java/com/mulkkam/ui/fixture/HistoryFixture.kt
  android/app/src/test/java/com/mulkkam/ui/history/HistoryViewModelTest.kt
Labels: AN, 💯 test

#455 [AN][refactor] 몸무게 최대치 수정
  android/app/src/main/java/com/mulkkam/domain/model/bio/BioWeight.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/bioinfo/BioInfoViewModel.kt
  android/app/src/main/java/com/mulkkam/ui/settingbioinfo/SettingBioInfoViewModel.kt
Labels: AN, ♻️ refactor

#467 [AN][feat]: 온보딩 약관 페이지로 이동하는 버튼 추가
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/mulkkam/ui/main/MainActivity.kt
  android/app/src/main/java/com/mulkkam/ui/main/MainViewModel.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/terms/TermsAgreementUiModel.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/terms/TermsFragment.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/terms/TermsViewModel.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/terms/adapter/TermsAgreementViewHolder.kt
  android/app/src/main/java/com/mulkkam/ui/util/extensions/ContextExtensions.kt
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/values/uris.xml
Labels: AN, 🍯 feat

#475 [AN][feat]: 기록 화면 Loading State 구현
  android/app/build.gradle.kts
  android/app/src/main/java/com/mulkkam/ui/history/HistoryFragment.kt
  android/app/src/main/java/com/mulkkam/ui/history/HistoryViewModel.kt
  android/app/src/main/res/layout/fragment_history.xml
  android/app/src/main/res/layout/layout_history_shimmer.xml
  android/app/src/test/java/com/mulkkam/ui/history/HistoryViewModelTest.kt
  android/gradle/libs.versions.toml
Labels: AN, 🍯 feat

#472 [AN][feat]: 목표 음용량 정책 반영
  android/app/src/main/java/com/mulkkam/domain/model/intake/TargetAmount.kt
  android/app/src/main/java/com/mulkkam/domain/model/result/MulKkamError.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/nickname/NicknameFragment.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/targetamount/TargetAmountFragment.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/targetamount/TargetAmountViewModel.kt
  android/app/src/main/java/com/mulkkam/ui/settingnickname/SettingNicknameActivity.kt
  android/app/src/main/java/com/mulkkam/ui/settingtargetamount/SettingTargetAmountActivity.kt
  android/app/src/main/java/com/mulkkam/ui/settingtargetamount/SettingTargetAmountViewModel.kt
  android/app/src/main/res/layout/activity_setting_target_amount.xml
  android/app/src/main/res/layout/fragment_target_amount.xml
  android/app/src/main/res/values/strings.xml
Labels: AN, 🍯 feat

#493 [BE][feat]: 로깅 구조 개선
  backend/src/main/java/backend/mulkkam/common/filter/HttpLoggingFilter.java
Labels: BE, ♻️ refactor

#483 [AN][feat]: 설정 화면 Loading State 구현
  android/app/src/main/java/com/mulkkam/domain/model/intake/TargetAmount.kt
  android/app/src/main/java/com/mulkkam/ui/history/HistoryFragment.kt
  android/app/src/main/java/com/mulkkam/ui/history/HistoryViewModel.kt
  android/app/src/main/java/com/mulkkam/ui/home/HomeFragment.kt
  android/app/src/main/java/com/mulkkam/ui/home/HomeViewModel.kt
  android/app/src/main/java/com/mulkkam/ui/model/MulKkamUiState.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/nickname/NicknameFragment.kt
  android/app/src/main/java/com/mulkkam/ui/settingbioinfo/SettingBioInfoActivity.kt
  android/app/src/main/java/com/mulkkam/ui/settingbioinfo/SettingBioInfoViewModel.kt
  android/app/src/main/java/com/mulkkam/ui/settingcups/SettingCupsActivity.kt
  android/app/src/main/java/com/mulkkam/ui/settingcups/SettingCupsViewModel.kt
  android/app/src/main/java/com/mulkkam/ui/settingnickname/SettingNicknameActivity.kt
  android/app/src/main/java/com/mulkkam/ui/settingnickname/SettingNicknameViewModel.kt
  android/app/src/main/java/com/mulkkam/ui/settingtargetamount/SettingTargetAmountActivity.kt
  android/app/src/main/java/com/mulkkam/ui/settingtargetamount/SettingTargetAmountViewModel.kt
  android/app/src/main/java/com/mulkkam/ui/settingtargetamount/model/TargetAmountUiModel.kt
  android/app/src/main/res/layout/activity_setting_cups.xml
  android/app/src/main/res/layout/fragment_home.xml
  android/app/src/main/res/layout/layout_history_shimmer.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/test/java/com/mulkkam/ui/history/HistoryViewModelTest.kt
Labels: AN, 🍯 feat

#488 [BE][feat]: 액세스 토큰 재발급 API 추가
  backend/src/main/java/backend/mulkkam/auth/controller/AuthController.java
  backend/src/main/java/backend/mulkkam/auth/domain/AccountRefreshToken.java
  backend/src/main/java/backend/mulkkam/auth/dto/request/KakaoSigninRequest.java
  backend/src/main/java/backend/mulkkam/auth/dto/request/ReissueTokenRequest.java
  backend/src/main/java/backend/mulkkam/auth/dto/response/OauthLoginResponse.java
  backend/src/main/java/backend/mulkkam/auth/dto/response/ReissueTokenResponse.java
  backend/src/main/java/backend/mulkkam/auth/infrastructure/OauthJwtTokenHandler.java
  backend/src/main/java/backend/mulkkam/auth/repository/AccountRefreshTokenRepository.java
  backend/src/main/java/backend/mulkkam/auth/service/AuthTokenService.java
  backend/src/main/java/backend/mulkkam/auth/service/KakaoAuthService.java
  backend/src/main/java/backend/mulkkam/common/exception/InvalidTokenException.java
  backend/src/main/java/backend/mulkkam/common/exception/errorCode/BadRequestErrorCode.java
  backend/src/main/java/backend/mulkkam/common/exception/errorCode/UnauthorizedErrorCode.java
  backend/src/main/java/backend/mulkkam/common/filter/JwtAuthenticationFilter.java
  backend/src/main/java/backend/mulkkam/common/resolver/MemberResolver.java
  backend/src/main/java/backend/mulkkam/common/resolver/OauthAccountResolver.java
  backend/src/test/java/backend/mulkkam/auth/controller/AuthControllerTest.java
  backend/src/test/java/backend/mulkkam/auth/infrastructure/OauthJwtTokenHandlerTest.java
  backend/src/test/java/backend/mulkkam/auth/service/KakaoAuthServiceIntegrationTest.java
  backend/src/test/java/backend/mulkkam/common/resolver/MemberResolverTest.java
  backend/src/test/java/backend/mulkkam/common/resolver/OauthAccountResolverTest.java
Labels: BE, 🍯 feat

#500 [BE][feat]: 마케팅 수신 알림 수정 로직 구현
  backend/src/main/java/backend/mulkkam/member/controller/MemberController.java
  backend/src/main/java/backend/mulkkam/member/domain/Member.java
  backend/src/main/java/backend/mulkkam/member/dto/request/ModifyIsMarketingNotificationAgreedRequest.java
  backend/src/main/java/backend/mulkkam/member/service/MemberService.java
  backend/src/test/java/backend/mulkkam/member/controller/MemberControllerTest.java
Labels: BE, 🍯 feat

#502 [BE][feat]: 로그아웃 API 추가
  backend/src/main/java/backend/mulkkam/auth/controller/AuthController.java
  backend/src/main/java/backend/mulkkam/auth/infrastructure/OauthJwtTokenHandler.java
  backend/src/main/java/backend/mulkkam/auth/repository/AccountRefreshTokenRepository.java
  backend/src/main/java/backend/mulkkam/auth/service/AuthTokenService.java
  backend/src/main/java/backend/mulkkam/common/exception/InvalidTokenException.java
  backend/src/main/java/backend/mulkkam/common/exception/errorCode/BadRequestErrorCode.java
  backend/src/main/java/backend/mulkkam/common/filter/JwtAuthenticationFilter.java
  backend/src/test/java/backend/mulkkam/auth/controller/AuthControllerTest.java
  backend/src/test/java/backend/mulkkam/auth/infrastructure/OauthJwtTokenHandlerTest.java
Labels: BE, 🍯 feat

#514 [AN][refactor]: 로그 표준시 변경
  android/app/src/main/java/com/mulkkam/data/logger/LoggerImpl.kt
  android/app/src/main/java/com/mulkkam/data/logger/SensitiveInfoSanitizerImpl.kt
  android/app/src/main/java/com/mulkkam/domain/model/logger/LogEntry.kt
Labels: AN, ♻️ refactor

#523 [AN][feat]: 개빠른 설정 화면 구현
  android/app/src/main/java/com/mulkkam/domain/model/logger/LogEvent.kt
  android/app/src/main/java/com/mulkkam/ui/setting/SettingFragment.kt
  android/app/src/main/java/com/mulkkam/ui/setting/adapter/SettingAdapter.kt
  android/app/src/main/java/com/mulkkam/ui/setting/adapter/SettingDiffCallback.kt
  android/app/src/main/java/com/mulkkam/ui/setting/adapter/SettingItem.kt
  android/app/src/main/java/com/mulkkam/ui/setting/adapter/SettingViewType.kt
  android/app/src/main/java/com/mulkkam/ui/setting/adapter/SwitchViewHolder.kt
  android/app/src/main/java/com/mulkkam/ui/setting/model/SettingType.kt
  android/app/src/main/res/values/strings.xml
Labels: AN, 🍯 feat

#528 [BE][feat]: 멤버 알림 세팅 조회 로직
  backend/src/main/java/backend/mulkkam/member/controller/MemberController.java
  backend/src/main/java/backend/mulkkam/member/dto/response/NotificationSettingsResponse.java
  backend/src/main/java/backend/mulkkam/member/service/MemberService.java
  backend/src/test/java/backend/mulkkam/intake/controller/IntakeTargetAmountControllerTest.java
  backend/src/test/java/backend/mulkkam/member/controller/MemberControllerTest.java
Labels: BE, 🍯 feat

#532 [BE][feat]: 멤버 알림 세팅 조회 로직
  backend/src/main/java/backend/mulkkam/member/service/MemberService.java
Labels: BE, 🍯 feat

#529 [AN][feat]: 알림 설정 기능 구현
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/mulkkam/data/remote/model/request/members/MarketingNotificationAgreedRequest.kt
  android/app/src/main/java/com/mulkkam/data/remote/model/request/members/NightNotificationAgreedRequest.kt
  android/app/src/main/java/com/mulkkam/data/remote/model/response/notification/NotificationAgreedResponse.kt
  android/app/src/main/java/com/mulkkam/data/remote/service/MembersService.kt
  android/app/src/main/java/com/mulkkam/data/repository/MembersRepositoryImpl.kt
  android/app/src/main/java/com/mulkkam/domain/model/members/NotificationAgreedInfo.kt
  android/app/src/main/java/com/mulkkam/domain/repository/MembersRepository.kt
  android/app/src/main/java/com/mulkkam/ui/setting/SettingFragment.kt
  android/app/src/main/java/com/mulkkam/ui/setting/adapter/SettingItem.kt
  android/app/src/main/java/com/mulkkam/ui/setting/model/SettingType.kt
  android/app/src/main/java/com/mulkkam/ui/settingnotification/SettingNotificationActivity.kt
  android/app/src/main/java/com/mulkkam/ui/settingnotification/SettingNotificationViewModel.kt
  android/app/src/main/java/com/mulkkam/ui/settingnotification/adapter/NormalViewHolder.kt
  android/app/src/main/java/com/mulkkam/ui/settingnotification/adapter/SettingNotificationAdapter.kt
  android/app/src/main/java/com/mulkkam/ui/settingnotification/adapter/SettingNotificationDiffCallback.kt
  android/app/src/main/java/com/mulkkam/ui/settingnotification/adapter/SettingNotificationItem.kt
  android/app/src/main/java/com/mulkkam/ui/settingnotification/adapter/SettingNotificationViewHolder.kt
  android/app/src/main/java/com/mulkkam/ui/settingnotification/adapter/SettingNotificationViewType.kt
  android/app/src/main/java/com/mulkkam/ui/settingnotification/adapter/SwitchViewHolder.kt
  android/app/src/main/java/com/mulkkam/ui/settingnotification/model/SettingNotificationType.kt
  android/app/src/main/res/layout/activity_setting_notification.xml
  android/app/src/main/res/values/strings.xml
Labels: AN, 🍯 feat

#531 [BE][fix]: 리졸버에서 커스텀 예외 던지도록 수정
  backend/src/main/java/backend/mulkkam/common/resolver/MemberResolver.java
  backend/src/main/java/backend/mulkkam/common/resolver/OauthAccountResolver.java
Labels: BE, 🔨 fix

#525 [AN][feat]: 회원 탈퇴 구현
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/mulkkam/data/remote/service/AuthService.kt
  android/app/src/main/java/com/mulkkam/data/remote/service/MembersService.kt
  android/app/src/main/java/com/mulkkam/data/repository/AuthRepositoryImpl.kt
  android/app/src/main/java/com/mulkkam/data/repository/MembersRepositoryImpl.kt
  android/app/src/main/java/com/mulkkam/domain/repository/AuthRepository.kt
  android/app/src/main/java/com/mulkkam/domain/repository/MembersRepository.kt
  android/app/src/main/java/com/mulkkam/ui/setting/SettingFragment.kt
  android/app/src/main/java/com/mulkkam/ui/settingaccountinfo/SettingAccountInfoActivity.kt
  android/app/src/main/java/com/mulkkam/ui/settingaccountinfo/SettingAccountInfoViewModel.kt
  android/app/src/main/java/com/mulkkam/ui/settingaccountinfo/SettingAccountUiModel.kt
  android/app/src/main/java/com/mulkkam/ui/settingaccountinfo/adapter/AccountInfoAdapter.kt
  android/app/src/main/java/com/mulkkam/ui/settingaccountinfo/adapter/AccountInfoViewHolder.kt
  android/app/src/main/java/com/mulkkam/ui/settingaccountinfo/dialog/AccountDeleteDialogFragment.kt
  android/app/src/main/java/com/mulkkam/ui/settingaccountinfo/dialog/AccountLogoutDialogFragment.kt
  android/app/src/main/res/layout/activity_setting_account_info.xml
  android/app/src/main/res/layout/fragment_account_delete_dialog.xml
  android/app/src/main/res/layout/fragment_account_logout_dialog.xml
  android/app/src/main/res/values/strings.xml
Labels: AN, 🍯 feat

#530 [AN][feat]: 설정 뷰 고객센터 구현
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/mulkkam/ui/onboarding/OnboardingActivity.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/OnboardingStep.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/terms/TermsAgreementFragment.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/terms/TermsAgreementViewModel.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/terms/adapter/TermsAgreementAdapter.kt
  android/app/src/main/java/com/mulkkam/ui/setting/SettingFragment.kt
  android/app/src/main/java/com/mulkkam/ui/settingfeedback/SettingFeedbackActivity.kt
  android/app/src/main/java/com/mulkkam/ui/settingterms/SettingTermsActivity.kt
  android/app/src/main/java/com/mulkkam/ui/settingterms/SettingTermsViewModel.kt
  android/app/src/main/java/com/mulkkam/ui/settingterms/TermsUiModel.kt
  android/app/src/main/java/com/mulkkam/ui/settingterms/adapter/TermsAdapter.kt
  android/app/src/main/java/com/mulkkam/ui/settingterms/adapter/TermsViewHolder.kt
  android/app/src/main/java/com/mulkkam/ui/util/extensions/ContextExtensions.kt
  android/app/src/main/res/layout/activity_setting_feedback.xml
  android/app/src/main/res/layout/activity_setting_terms.xml
  android/app/src/main/res/layout/fragment_terms.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/values/uris.xml
Labels: AN, 🍯 feat

#547 [BE][ fix]: Member 리졸버에서 OauthAccount id 전달하는 문제
  backend/src/main/java/backend/mulkkam/common/exception/GlobalExceptionHandler.java
  backend/src/main/java/backend/mulkkam/common/filter/HttpLoggingFilter.java
  backend/src/main/java/backend/mulkkam/common/filter/JwtAuthenticationFilter.java
  backend/src/main/java/backend/mulkkam/common/interceptor/ApiPerformanceInterceptor.java
  backend/src/main/java/backend/mulkkam/common/resolver/MemberResolver.java
  backend/src/main/java/backend/mulkkam/common/resolver/OauthAccountResolver.java
  backend/src/test/java/backend/mulkkam/common/resolver/MemberResolverTest.java
  backend/src/test/java/backend/mulkkam/common/resolver/OauthAccountResolverTest.java
Labels: BE, 🔨 fix

#540 [AN][refactor]: 닉네임 입력 글자수 제한
  android/app/src/main/res/layout/activity_setting_nickname.xml
  android/app/src/main/res/layout/fragment_nickname.xml
Labels: AN, ♻️ refactor

#553 [BE][fix]: 음용 세부 기록 반환 정렬 기준 내림차순으로 변경
  backend/src/main/java/backend/mulkkam/intake/service/IntakeHistoryService.java
  backend/src/test/java/backend/mulkkam/intake/controller/IntakeAmountControllerTest.java
  backend/src/test/java/backend/mulkkam/intake/controller/IntakeHistoryControllerTest.java
  backend/src/test/java/backend/mulkkam/intake/service/IntakeHistoryServiceUnitTest.java
Labels: BE, 🍯 feat

#565 [BE][feat]: 몸무게 및 성별 null일 시, 기본값이 아닌 null 반환하도록 변경
  backend/src/main/java/backend/mulkkam/intake/domain/vo/RecommendAmount.java
  backend/src/main/java/backend/mulkkam/member/domain/vo/PhysicalAttributes.java
  backend/src/main/java/backend/mulkkam/member/dto/response/MemberResponse.java
  backend/src/test/java/backend/mulkkam/member/controller/MemberControllerTest.java
  backend/src/test/java/backend/mulkkam/member/service/MemberServiceIntegrationTest.java
  backend/src/test/java/backend/mulkkam/member/service/MemberServiceUnitTest.java
Labels: BE, 🍯 feat

#578 [BE][fix] dev profile 누락
  backend/src/main/resources/application-dev.yml
Labels: BE, 🚧 chore

#543 [AN][refactor]: 기록 화면에서 과거 기록 삭제 막기
  android/app/src/main/java/com/mulkkam/data/remote/model/error/ResponseError.kt
  android/app/src/main/java/com/mulkkam/domain/model/result/MulKkamError.kt
  android/app/src/main/java/com/mulkkam/ui/history/HistoryFragment.kt
  android/app/src/main/java/com/mulkkam/ui/history/HistoryViewModel.kt
  android/app/src/main/res/values/strings.xml
Labels: AN, ♻️ refactor

#551 [AN][feat]: 커스텀 스낵바 디자인 반영한 커스텀 토스트
  android/app/src/main/java/com/mulkkam/ui/custom/snackbar/CustomSnackBar.kt
  android/app/src/main/java/com/mulkkam/ui/custom/toast/CustomToast.kt
  android/app/src/main/java/com/mulkkam/ui/main/MainActivity.kt
  android/app/src/main/java/com/mulkkam/ui/notification/NotificationActivity.kt
  android/app/src/main/java/com/mulkkam/ui/notification/adapter/NotificationViewHolder.kt
  android/app/src/main/java/com/mulkkam/ui/settingaccountinfo/SettingAccountInfoActivity.kt
  android/app/src/main/java/com/mulkkam/ui/settingcups/dialog/SettingCupFragment.kt
  android/app/src/main/java/com/mulkkam/ui/settingnickname/SettingNicknameActivity.kt
  android/app/src/main/java/com/mulkkam/ui/settingtargetamount/SettingTargetAmountActivity.kt
  android/app/src/main/res/drawable/ic_history_delete_warning_sign.xml
  android/app/src/main/res/drawable/ic_onboarding_complete.gif
  android/app/src/main/res/layout/fragment_account_delete_dialog.xml
  android/app/src/main/res/layout/fragment_account_logout_dialog.xml
  android/app/src/main/res/layout/fragment_delete_confirm_dialog.xml
  android/app/src/main/res/layout/layout_custom_toast.xml
Labels: AN, 🍯 feat

#495 [AN][feat]: 기록 화면 주간 차트 상단에 고정
  android/app/src/main/res/layout/fragment_history.xml
  android/app/src/main/res/values/strings.xml
Labels: AN, 🍯 feat

#479 [AN][refactor]: EditText 넘어갈 시 오류 수정, 키보드 완료 버튼 클릭 시 키보드 숨김
  android/app/src/main/java/com/mulkkam/ui/home/dialog/ManualDrinkFragment.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/nickname/NicknameFragment.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/targetamount/TargetAmountFragment.kt
  android/app/src/main/java/com/mulkkam/ui/settingcups/dialog/SettingCupFragment.kt
  android/app/src/main/java/com/mulkkam/ui/settingnickname/SettingNicknameActivity.kt
  android/app/src/main/java/com/mulkkam/ui/settingtargetamount/SettingTargetAmountActivity.kt
  android/app/src/main/java/com/mulkkam/ui/util/extensions/ViewExtensions.kt
  android/app/src/main/res/layout/activity_setting_nickname.xml
  android/app/src/main/res/layout/fragment_nickname.xml
  android/app/src/main/res/layout/fragment_setting_cup.xml
Labels: AN, ♻️ refactor

#569 [AN][feat]: 헬스 및 알림 권한 위치 이동
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/mulkkam/data/local/preference/MembersPreference.kt
  android/app/src/main/java/com/mulkkam/data/local/preference/TokenPreference.kt
  android/app/src/main/java/com/mulkkam/data/repository/MembersRepositoryImpl.kt
  android/app/src/main/java/com/mulkkam/data/repository/TokenRepositoryImpl.kt
  android/app/src/main/java/com/mulkkam/di/PreferenceInjection.kt
  android/app/src/main/java/com/mulkkam/di/RepositoryInjection.kt
  android/app/src/main/java/com/mulkkam/domain/repository/MembersRepository.kt
  android/app/src/main/java/com/mulkkam/ui/main/MainActivity.kt
  android/app/src/main/java/com/mulkkam/ui/main/MainViewModel.kt
  android/app/src/main/java/com/mulkkam/ui/main/dialog/MainPermissionDialogFragment.kt
  android/app/src/main/java/com/mulkkam/ui/settingbioinfo/SettingBioInfoActivity.kt
  android/app/src/main/res/drawable/ic_manual_drink.png
  android/app/src/main/res/drawable/ic_manual_drink.xml
  android/app/src/main/res/drawable/ic_permission_health.xml
  android/app/src/main/res/drawable/ic_permission_notification.xml
  android/app/src/main/res/layout/fragment_main_permission.xml
  android/app/src/main/res/values/strings.xml
Labels: AN, 🍯 feat

#557 [AN][feat]: 컵 용량 및 직접 입력 유효성 검증 추가
  android/app/src/main/java/com/mulkkam/data/remote/model/error/ResponseError.kt
  android/app/src/main/java/com/mulkkam/data/remote/model/request/cups/NewCupRequest.kt
  android/app/src/main/java/com/mulkkam/data/remote/model/request/cups/PatchCupRequest.kt
  android/app/src/main/java/com/mulkkam/data/remote/model/response/cups/CupResponse.kt
  android/app/src/main/java/com/mulkkam/data/repository/CupsRepositoryImpl.kt
  android/app/src/main/java/com/mulkkam/data/repository/IntakeRepositoryImpl.kt
  android/app/src/main/java/com/mulkkam/domain/model/cups/Cup.kt
  android/app/src/main/java/com/mulkkam/domain/model/cups/CupAmount.kt
  android/app/src/main/java/com/mulkkam/domain/model/cups/CupName.kt
  android/app/src/main/java/com/mulkkam/domain/model/intake/TargetAmount.kt
  android/app/src/main/java/com/mulkkam/domain/model/result/MulKkamError.kt
  android/app/src/main/java/com/mulkkam/domain/repository/IntakeRepository.kt
  android/app/src/main/java/com/mulkkam/ui/home/HomeFragment.kt
  android/app/src/main/java/com/mulkkam/ui/home/HomeViewModel.kt
  android/app/src/main/java/com/mulkkam/ui/home/dialog/ManualDrinkFragment.kt
  android/app/src/main/java/com/mulkkam/ui/home/dialog/ManualDrinkViewModel.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/targetamount/TargetAmountFragment.kt
  android/app/src/main/java/com/mulkkam/ui/settingcups/adapter/CupViewHolder.kt
  android/app/src/main/java/com/mulkkam/ui/settingcups/dialog/SettingCupFragment.kt
  android/app/src/main/java/com/mulkkam/ui/settingcups/dialog/SettingCupViewModel.kt
  android/app/src/main/java/com/mulkkam/ui/settingcups/model/CupUiModel.kt
  android/app/src/main/java/com/mulkkam/ui/settingtargetamount/SettingTargetAmountActivity.kt
  android/app/src/main/java/com/mulkkam/ui/util/extensions/StringExtensions.kt
  android/app/src/main/res/layout/fragment_manual_drink.xml
  android/app/src/main/res/layout/fragment_setting_cup.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/test/java/com/mulkkam/domain/cups/CupNameTest.kt
Labels: AN, 🍯 feat

#608 [BE][fix]: 최초 회원가입/로그인 시 member id 값 미결정되어 404 에러 뜨는 문제 해결
  backend/src/main/java/backend/mulkkam/common/resolver/MemberResolver.java
  backend/src/test/java/backend/mulkkam/common/resolver/MemberResolverTest.java
Labels: BE, 🔨 fix

#614 [BE][fix]: release 브랜치 상에서 CD 트리거가 안되는 오류 해결
  .github/workflows/backend-prod-cd.yml
Labels: BE, 🔨 fix

#620 [BE][chore]: 프로덕션 수동 롤백 스크립트 추가
  .github/workflows/backend-prod-rollback.yml
Labels: BE, 🚧 chore

#622 [BE][chore]: 프로덕션 수동 롤백 스크립트 추가
  .github/workflows/backend-prod-rollback.yml
  .github/workflows/develop-pr-branch-guard.yml
Labels: BE, 🚧 chore

#627 [BE][fix]: 수동 롤백 스크립트 경로 오류 수정
  .github/workflows/backend-prod-rollback.yml
Labels: BE, 🚧 chore

#628 [BE][chore]: 프로덕션 수동 롤백 스크립트 추가
  .github/workflows/backend-prod-rollback.yml
Labels: BE, 🚧 chore

#631 [BE][chore]: 프로덕션 수동 롤백 스크립트 추가
  .github/workflows/backend-prod-rollback.yml
Labels: BE, 🚧 chore

#633 [BE][chore]: 프로덕션 수동 롤백 스크립트 추가
  .github/workflows/backend-prod-rollback.yml
Labels: BE, 🚧 chore

#636 [chore] develop 브랜치로 develop-be 머지
  .github/workflows/backend-dev-cd.yml
  .github/workflows/backend-prod-rollback.yml
  backend/src/main/java/backend/mulkkam/common/config/datasource/DataSourceConfig.java
  backend/src/main/java/backend/mulkkam/common/config/datasource/DatabaseRole.java
  backend/src/main/java/backend/mulkkam/common/config/datasource/ReadWriteRoutingDataSource.java
  backend/src/main/resources/application-dev.yml
Labels: BE, 🚧 chore

#600 [AN][refactor]: 알림 목표량 반영 API 변경
  android/app/src/main/java/com/mulkkam/data/remote/model/response/notification/NotificationsResponse.kt
  android/app/src/main/java/com/mulkkam/data/remote/model/response/notification/ReadNotificationResponse.kt
  android/app/src/main/java/com/mulkkam/data/remote/service/IntakeService.kt
  android/app/src/main/java/com/mulkkam/data/remote/service/NotificationsService.kt
  android/app/src/main/java/com/mulkkam/data/repository/IntakeRepositoryImpl.kt
  android/app/src/main/java/com/mulkkam/data/repository/NotificationRepositoryImpl.kt
  android/app/src/main/java/com/mulkkam/domain/model/notification/Notification.kt
  android/app/src/main/java/com/mulkkam/domain/repository/IntakeRepository.kt
  android/app/src/main/java/com/mulkkam/domain/repository/NotificationRepository.kt
  android/app/src/main/java/com/mulkkam/ui/notification/NotificationViewModel.kt
  android/app/src/main/java/com/mulkkam/ui/notification/adapter/NotificationViewHolder.kt
  android/app/src/main/res/drawable/ic_notification_notice.xml
  android/app/src/main/res/drawable/ic_notification_remind.xml
  android/app/src/main/res/drawable/ic_notification_suggestion.xml
  android/app/src/main/res/layout/item_home_notification.xml
Labels: AN, ♻️ refactor

#567 [BE][feat]: 음용 타입에 따른 적용 음용량 구현
  backend/src/main/java/backend/mulkkam/cup/domain/IntakeType.java
  backend/src/main/java/backend/mulkkam/intake/controller/IntakeHistoryController.java
  backend/src/main/java/backend/mulkkam/intake/domain/IntakeHistoryDetail.java
  backend/src/main/java/backend/mulkkam/intake/domain/vo/Amount.java
  backend/src/main/java/backend/mulkkam/intake/dto/request/CreateIntakeHistoryDetailRequest.java
  backend/src/main/java/backend/mulkkam/intake/dto/response/IntakeHistoryDetailResponse.java
  backend/src/main/java/backend/mulkkam/intake/dto/response/IntakeHistorySummaryResponse.java
  backend/src/main/java/backend/mulkkam/intake/service/IntakeHistoryService.java
  backend/src/main/resources/db/migration/common/V16__modify_intake_history_detail.sql
  backend/src/test/java/backend/mulkkam/cup/domain/IntakeTypeTest.java
  backend/src/test/java/backend/mulkkam/intake/controller/IntakeHistoryControllerTest.java
  backend/src/test/java/backend/mulkkam/intake/service/IntakeHistoryServiceIntegrationTest.java
  backend/src/test/java/backend/mulkkam/intake/service/IntakeHistoryServiceUnitTest.java
  backend/src/test/java/backend/mulkkam/support/IntakeHistoryDetailFixtureBuilder.java
Labels: BE, 🍯 feat

#612 [AN][feat]: 1x4 위젯 구현
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/mulkkam/data/checker/CalorieCheckerImpl.kt
  android/app/src/main/java/com/mulkkam/data/checker/IntakeCheckerImpl.kt
  android/app/src/main/java/com/mulkkam/data/checker/ProgressCheckerImpl.kt
  android/app/src/main/java/com/mulkkam/data/work/DrinkByAmountWorker.kt
  android/app/src/main/java/com/mulkkam/data/work/IntakeWidgetWorker.kt
  android/app/src/main/java/com/mulkkam/data/work/ProgressWorker.kt
  android/app/src/main/java/com/mulkkam/data/work/WorkerFactory.kt
  android/app/src/main/java/com/mulkkam/di/CheckerInjection.kt
  android/app/src/main/java/com/mulkkam/di/WorkInjection.kt
  android/app/src/main/java/com/mulkkam/domain/checker/CalorieChecker.kt
  android/app/src/main/java/com/mulkkam/domain/checker/IntakeChecker.kt
  android/app/src/main/java/com/mulkkam/domain/checker/ProgressChecker.kt
  android/app/src/main/java/com/mulkkam/domain/model/cups/Cups.kt
  android/app/src/main/java/com/mulkkam/domain/work/CalorieScheduler.kt
  android/app/src/main/java/com/mulkkam/ui/custom/floatingactionbutton/ExtendableFloatingActionButton.kt
  android/app/src/main/java/com/mulkkam/ui/custom/progress/GradientDonutChartView.kt
  android/app/src/main/java/com/mulkkam/ui/main/MainActivity.kt
  android/app/src/main/java/com/mulkkam/ui/main/MainViewModel.kt
  android/app/src/main/java/com/mulkkam/ui/util/ViewBitmapCapture.kt
  android/app/src/main/java/com/mulkkam/ui/util/extensions/FloatExtensions.kt
  android/app/src/main/java/com/mulkkam/ui/util/extensions/IntExtensions.kt
  android/app/src/main/java/com/mulkkam/ui/util/extensions/ViewExtensions.kt
  android/app/src/main/java/com/mulkkam/ui/widget/IntakeWidget.kt
  android/app/src/main/java/com/mulkkam/ui/widget/IntakeWidgetAction.kt
  android/app/src/main/java/com/mulkkam/ui/widget/ProgressWidget.kt
  android/app/src/main/res/drawable/bg_common_rectangle_10dp.xml
  android/app/src/main/res/drawable/bg_common_rectangle_stroke_10dp.xml
  android/app/src/main/res/drawable/img_intake_widget.png
  android/app/src/main/res/drawable/img_progress_widget.png
  android/app/src/main/res/layout/layout_intake_widget.xml
  android/app/src/main/res/layout/layout_progress_widget.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/xml/intake_widget_info.xml
  android/app/src/main/res/xml/progress_widget_info.xml
Labels: AN, 🍯 feat

#518 [BE][feat]: 버전 확인 기능 구현
  backend/src/main/java/backend/mulkkam/common/exception/errorCode/NotFoundErrorCode.java
  backend/src/main/java/backend/mulkkam/common/filter/JwtAuthenticationFilter.java
  backend/src/main/java/backend/mulkkam/version/controller/AppMinimumVersionController.java
  backend/src/main/java/backend/mulkkam/version/domain/AppMinimumVersion.java
  backend/src/main/java/backend/mulkkam/version/dto/AppMinimumVersionResponse.java
  backend/src/main/java/backend/mulkkam/version/repository/AppMinimumVersionRepository.java
  backend/src/main/java/backend/mulkkam/version/service/AppMinimumVersionService.java
  backend/src/main/resources/db/migration/common/V17__add_app_minimum_version.sql
  backend/src/test/java/backend/mulkkam/auth/controller/AuthControllerTest.java
  backend/src/test/java/backend/mulkkam/cup/controller/CupControllerTest.java
  backend/src/test/java/backend/mulkkam/intake/controller/IntakeAmountControllerTest.java
  backend/src/test/java/backend/mulkkam/intake/controller/IntakeHistoryControllerTest.java
  backend/src/test/java/backend/mulkkam/member/controller/MemberControllerTest.java
  backend/src/test/java/backend/mulkkam/notification/controller/NotificationControllerTest.java
  backend/src/test/java/backend/mulkkam/notification/controller/SuggestionNotificationControllerTest.java
  backend/src/test/java/backend/mulkkam/support/AppMinimumVersionFixtureBuilder.java
  backend/src/test/java/backend/mulkkam/support/ControllerTest.java
  backend/src/test/java/backend/mulkkam/version/controller/AppMinimumVersionControllerTest.java
  backend/src/test/java/backend/mulkkam/version/repository/AppMinimumVersionRepositoryTest.java
Labels: BE, 🍯 feat

#594 [BE][fix]: 알림 조회 기능 시 새로운 알림은 조회한 이후 isRead 처리하기
  backend/src/main/java/backend/mulkkam/notification/service/NotificationService.java
  backend/src/test/java/backend/mulkkam/notification/controller/NotificationControllerTest.java
  backend/src/test/java/backend/mulkkam/notification/service/NotificationServiceIntegrationTest.java
  backend/src/test/java/backend/mulkkam/notification/service/NotificationServiceUnitTest.java
Labels: BE, 🔨 fix

#641 [BE][feat]: 알림 삭제 기능 구현
  .github/workflows/develop-pr-branch-guard.yml
  .github/workflows/tag-on-release-merge.yml
  backend/src/main/java/backend/mulkkam/common/exception/errorCode/ForbiddenErrorCode.java
  backend/src/main/java/backend/mulkkam/common/exception/errorCode/NotFoundErrorCode.java
  backend/src/main/java/backend/mulkkam/notification/controller/NotificationController.java
  backend/src/main/java/backend/mulkkam/notification/domain/Notification.java
  backend/src/main/java/backend/mulkkam/notification/repository/NotificationRepository.java
  backend/src/main/java/backend/mulkkam/notification/service/NotificationService.java
  backend/src/test/java/backend/mulkkam/notification/controller/NotificationControllerTest.java
  backend/src/test/java/backend/mulkkam/notification/service/NotificationServiceIntegrationTest.java
Labels: BE, 🍯 feat

#642 [AN][refactor]: 기록 화면 sticky header 수정
  android/app/src/main/java/com/mulkkam/ui/history/HistoryFragment.kt
  android/app/src/main/res/layout/fragment_history.xml
Labels: AN, ♻️ refactor

#650 [AN][feat]: 기록 화면 이모지 출력 및 액체 타입에 따른 색깔 변경
  android/app/src/main/java/com/mulkkam/data/remote/model/response/intake/IntakeHistoryResponse.kt
  android/app/src/main/java/com/mulkkam/domain/model/intake/IntakeHistory.kt
  android/app/src/main/java/com/mulkkam/ui/history/adapter/HistoryViewHolder.kt
  android/app/src/main/res/layout/item_intake_history.xml
  android/app/src/test/java/com/mulkkam/ui/fixture/HistoryFixture.kt
Labels: AN, 🍯 feat

#654 [AN][fix]: CI에 잘못 들어간 키값 수정
  .github/workflows/android-ci.yml
Labels: AN, 🔨 fix

#644 [AN][feat]: 강제 업데이트 구현
  android/app/src/main/java/com/mulkkam/data/remote/model/response/MinimumVersionResponse.kt
  android/app/src/main/java/com/mulkkam/data/remote/service/VersionsService.kt
  android/app/src/main/java/com/mulkkam/data/repository/VersionsRepositoryImpl.kt
  android/app/src/main/java/com/mulkkam/di/RepositoryInjection.kt
  android/app/src/main/java/com/mulkkam/di/ServiceInjection.kt
  android/app/src/main/java/com/mulkkam/domain/repository/VersionsRepository.kt
  android/app/src/main/java/com/mulkkam/ui/login/LoginActivity.kt
  android/app/src/main/java/com/mulkkam/ui/login/LoginViewModel.kt
  android/app/src/main/java/com/mulkkam/ui/main/MainActivity.kt
  android/app/src/main/java/com/mulkkam/ui/main/MainViewModel.kt
  android/app/src/main/java/com/mulkkam/ui/main/dialog/MainPermissionDialogFragment.kt
  android/app/src/main/java/com/mulkkam/ui/splash/dialog/AppUpdateDialogFragment.kt
  android/app/src/main/java/com/mulkkam/ui/util/extensions/ContextExtensions.kt
  android/app/src/main/res/drawable/img_app_update.xml
  android/app/src/main/res/layout/dialog_fragment_app_update.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/values/uris.xml
Labels: AN, 🍯 feat

#660 [BE][fix]: 컵 섭취 API 요청 형식 변경
  backend/src/main/java/backend/mulkkam/intake/dto/request/CreateIntakeHistoryDetailByCupRequest.java
  backend/src/test/java/backend/mulkkam/intake/controller/IntakeHistoryControllerTest.java
  backend/src/test/java/backend/mulkkam/intake/service/IntakeHistoryServiceIntegrationTest.java
Labels: BE, 🔨 fix

#666 [AN][feat]: 컵 설정 화면에 이모지 추가
  android/app/build.gradle.kts
  android/app/src/main/java/com/mulkkam/data/remote/model/request/cups/NewCupRequest.kt
  android/app/src/main/java/com/mulkkam/data/remote/model/request/cups/PatchCupRequest.kt
  android/app/src/main/java/com/mulkkam/data/remote/model/response/cups/CupEmojiResponse.kt
  android/app/src/main/java/com/mulkkam/data/remote/model/response/cups/CupEmojisResponse.kt
  android/app/src/main/java/com/mulkkam/data/remote/service/CupsService.kt
  android/app/src/main/java/com/mulkkam/data/repository/CupsRepositoryImpl.kt
  android/app/src/main/java/com/mulkkam/domain/model/cups/CupEmoji.kt
  android/app/src/main/java/com/mulkkam/domain/repository/CupsRepository.kt
  android/app/src/main/java/com/mulkkam/ui/custom/floatingactionbutton/ExtendableFloatingMenu.kt
  android/app/src/main/java/com/mulkkam/ui/history/adapter/HistoryViewHolder.kt
  android/app/src/main/java/com/mulkkam/ui/login/LoginViewModel.kt
  android/app/src/main/java/com/mulkkam/ui/main/MainViewModel.kt
  android/app/src/main/java/com/mulkkam/ui/settingcups/adapter/CupViewHolder.kt
  android/app/src/main/java/com/mulkkam/ui/settingcups/dialog/SettingCupFragment.kt
  android/app/src/main/java/com/mulkkam/ui/settingcups/dialog/SettingCupViewModel.kt
  android/app/src/main/java/com/mulkkam/ui/settingcups/dialog/adpater/CupEmojiAdapter.kt
  android/app/src/main/java/com/mulkkam/ui/settingcups/dialog/adpater/CupEmojiDiff.kt
  android/app/src/main/java/com/mulkkam/ui/settingcups/dialog/adpater/CupEmojiViewHolder.kt
  android/app/src/main/java/com/mulkkam/ui/settingcups/dialog/model/CupEmojiUiModel.kt
  android/app/src/main/java/com/mulkkam/ui/settingcups/dialog/model/CupEmojisUiModel.kt
  android/app/src/main/java/com/mulkkam/ui/util/ImageShape.kt
  android/app/src/main/java/com/mulkkam/ui/util/extensions/ImageViewExtensions.kt
  android/app/src/main/java/com/mulkkam/ui/util/glide/SvgDecoder.kt
  android/app/src/main/java/com/mulkkam/ui/util/glide/SvgDrawableTranscoder.kt
  android/app/src/main/java/com/mulkkam/ui/util/glide/SvgModule.kt
  android/app/src/main/java/com/mulkkam/ui/util/glide/SvgSoftwareLayerSetter.kt
  android/app/src/main/res/drawable/selector_setting_cup_emoji.xml
  android/app/src/main/res/layout/fragment_setting_cup.xml
  android/app/src/main/res/layout/item_cup_emoji.xml
  android/app/src/main/res/layout/item_setting_cups_cup.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/test/java/com/mulkkam/domain/cups/CupEmojiNameTest.kt
  android/gradle/libs.versions.toml
Labels: AN, 🍯 feat

#482 [AN][test]: Domain model 테스트 코드 작성
  android/app/src/main/java/com/mulkkam/data/remote/model/request/members/MembersRequest.kt
  android/app/src/main/java/com/mulkkam/data/remote/model/response/members/MembersResponse.kt
  android/app/src/main/java/com/mulkkam/domain/model/intake/IntakeHistorySummaries.kt
  android/app/src/main/java/com/mulkkam/domain/model/members/MemberInfo.kt
  android/app/src/main/java/com/mulkkam/domain/model/members/OnboardingInfo.kt
  android/app/src/main/java/com/mulkkam/ui/history/HistoryFragment.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/OnboardingViewModel.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/dialog/CompleteDialogFragment.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/targetamount/TargetAmountFragment.kt
  android/app/src/test/java/com/mulkkam/domain/model/bio/BioWeightTest.kt
  android/app/src/test/java/com/mulkkam/domain/model/bio/GenderTest.kt
  android/app/src/test/java/com/mulkkam/domain/model/cups/CupsTest.kt
  android/app/src/test/java/com/mulkkam/domain/model/intake/IntakeHistorySummariesTest.kt
  android/app/src/test/java/com/mulkkam/domain/model/intake/IntakeHistorySummaryTest.kt
  android/app/src/test/java/com/mulkkam/domain/model/intake/IntakeTypeTest.kt
  android/app/src/test/java/com/mulkkam/domain/model/member/NicknameTest.kt
  android/app/src/test/java/com/mulkkam/domain/model/member/OnboardingInfoTest.kt
  android/app/src/test/java/com/mulkkam/domain/model/notififcation/NotificationTypeTest.kt
  android/app/src/test/java/com/mulkkam/fixture/CupFixture.kt
  android/app/src/test/java/com/mulkkam/fixture/HistoryFixture.kt
  android/app/src/test/java/com/mulkkam/ui/history/HistoryViewModelTest.kt
Labels: AN, 💯 test

#674 [BE][fix]: 음용 타입에 따른 음용량 적용 구현
  backend/src/main/java/backend/mulkkam/cup/domain/Cup.java
  backend/src/main/java/backend/mulkkam/cup/dto/request/CreateCupRequest.java
  backend/src/main/java/backend/mulkkam/cup/service/CupService.java
  backend/src/main/java/backend/mulkkam/intake/controller/IntakeHistoryController.java
  backend/src/main/java/backend/mulkkam/intake/domain/IntakeHistoryDetail.java
  backend/src/main/java/backend/mulkkam/intake/dto/request/CreateIntakeHistoryDetailByCupRequest.java
  backend/src/main/java/backend/mulkkam/intake/dto/request/CreateIntakeHistoryDetailByUserInputRequest.java
  backend/src/main/java/backend/mulkkam/intake/service/IntakeHistoryService.java
  backend/src/test/java/backend/mulkkam/intake/service/IntakeHistoryServiceIntegrationTest.java
  backend/src/test/java/backend/mulkkam/support/IntakeHistoryDetailFixtureBuilder.java
Labels: BE, 🔨 fix

#678 [AN][fix]: 2차 QA 반영
  android/app/src/main/java/com/mulkkam/data/remote/model/response/intake/IntakeHistoryResultResponse.kt
  android/app/src/main/java/com/mulkkam/data/remote/model/response/notifications/NotificationAgreedResponse.kt
  android/app/src/main/java/com/mulkkam/data/remote/model/response/notifications/NotificationUnreadCountResponse.kt
  android/app/src/main/java/com/mulkkam/data/remote/model/response/notifications/NotificationsResponse.kt
  android/app/src/main/java/com/mulkkam/data/remote/model/response/notifications/ReadNotificationResponse.kt
  android/app/src/main/java/com/mulkkam/data/remote/model/response/versions/MinimumVersionResponse.kt
  android/app/src/main/java/com/mulkkam/data/remote/service/MembersService.kt
  android/app/src/main/java/com/mulkkam/data/remote/service/NotificationsService.kt
  android/app/src/main/java/com/mulkkam/data/remote/service/VersionsService.kt
  android/app/src/main/java/com/mulkkam/data/repository/MembersRepositoryImpl.kt
  android/app/src/main/java/com/mulkkam/data/repository/NotificationRepositoryImpl.kt
  android/app/src/main/java/com/mulkkam/data/work/IntakeWidgetWorker.kt
  android/app/src/main/java/com/mulkkam/domain/model/cups/Cup.kt
  android/app/src/main/java/com/mulkkam/domain/model/cups/Cups.kt
  android/app/src/main/java/com/mulkkam/domain/model/intake/IntakeHistoryResult.kt
  android/app/src/main/java/com/mulkkam/ui/history/HistoryFragment.kt
  android/app/src/main/java/com/mulkkam/ui/home/HomeFragment.kt
  android/app/src/main/java/com/mulkkam/ui/home/HomeViewModel.kt
  android/app/src/main/java/com/mulkkam/ui/home/dialog/ManualDrinkFragment.kt
  android/app/src/main/java/com/mulkkam/ui/notification/NotificationActivity.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/dialog/CompleteDialogFragment.kt
  android/app/src/main/java/com/mulkkam/ui/onboarding/targetamount/TargetAmountFragment.kt
  android/app/src/main/java/com/mulkkam/ui/settingcups/SettingCupsActivity.kt
  android/app/src/main/java/com/mulkkam/ui/settingcups/adapter/CupViewHolder.kt
  android/app/src/main/java/com/mulkkam/ui/settingcups/adapter/CupsItemTouchHelperCallback.kt
  android/app/src/main/java/com/mulkkam/ui/settingcups/dialog/SettingCupFragment.kt
  android/app/src/main/java/com/mulkkam/ui/settingcups/model/CupUiModel.kt
  android/app/src/main/java/com/mulkkam/ui/settingtargetamount/SettingTargetAmountActivity.kt
  android/app/src/main/res/drawable/img_history_sleeping_character.xml
  android/app/src/main/res/layout/item_setting_cups_cup.xml
  android/app/src/main/res/values/strings.xml
Labels: AN, 🔨 fix

#689 [BE][feat]: 로깅 처리 개선
  backend/src/main/java/backend/mulkkam/common/filter/HttpLoggingFilter.java
  backend/src/main/resources/logback-spring.xml
Labels: BE, ♻️ refactor
